In [4]:
import pandas as pd

In [ ]:
import pandas as pd
DimCategory = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimCategory.xlsx"
)

DimCustomer_Enterprise = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimCustomer_Enterprise.xlsx"
)

DimDate = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimDate.xlsx"
)

DimEmployee_Enterprise = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimEmployee_Enterprise.xlsx"
)

DimProduct_Enterprise = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimProduct_Enterprise.xlsx"
)

DimPromotion = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimPromotion.xlsx"
)

DimRegion = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimRegion.xlsx"
)

DimStore_Enterprise = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimStore_Enterprise.xlsx"
)

DimSupplier_Enterprise = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\DimSupplier_Enterprise.xlsx"
)

FactInventory = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactInventory.xlsx"
)

FactMarketing = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactMarketing.xlsx"
)

FactOrderDetails = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactOrderDetails.xlsx"
)

FactOrders = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactOrders.xlsx"
)

FactPayments = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactPayments.xlsx"
)

FactReturns = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactReturns.xlsx"
)

FactShipments = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactShipments.xlsx"
)

FactWebsiteTraffic = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactWebsiteTraffic.xlsx"
)

## Data Validation & Data Cleaning & Data Verification

## DimCategory

In [618]:
DimCategory["CategoryName"].duplicated().sum()

0

In [620]:
DimCategory["CategoryName"] = (
    DimCategory["CategoryName"]
    .str.strip()
    .str.title()
)

In [622]:
DimCategory[
    ~DimCategory["CategoryName"].str.match(r"^[A-Za-z &]+$", na=False)
]

Empty DataFrame
Columns: [CategoryID, CategoryName]
Index: []

## DimRegion

In [630]:
DimRegion["RegionName"].duplicated().sum()

0

In [633]:
DimRegion["RegionName"] = (
    DimRegion["RegionName"]
        .str.strip()
        .str.title()
)

DimRegion["Zone"] = (
    DimRegion["Zone"]
        .str.strip()
        .str.title()
)

In [635]:
invalid_regions = DimRegion[
    ~DimRegion["RegionName"].str.match(r"^[A-Za-z &]+$", na=False)
]

print(invalid_regions)

Empty DataFrame
Columns: [RegionID, RegionName, Zone]
Index: []

In [637]:
valid_zones = ["North", "South", "East", "West"]

invalid_zones = DimRegion[
    ~DimRegion["Zone"].isin(valid_zones)
]

print(invalid_zones)

Empty DataFrame
Columns: [RegionID, RegionName, Zone]
Index: []

## DimPromotion

In [640]:
DimPromotion[
    DimPromotion["CampaignName"].duplicated(keep=False)
].sort_values("CampaignName")

,PromotionID,CampaignName,DiscountPercent,StartDate,EndDate,PromotionType
54,55,Mega Festival Sale,50,2024-02-04,2024-02-27,BOGO
55,56,Mega Festival Sale,50,2024-03-09,2024-04-20,Flat

In [642]:
DimPromotion["StartDate"] = pd.to_datetime(
    DimPromotion["StartDate"],
    errors="coerce"
)

DimPromotion["EndDate"] = pd.to_datetime(
    DimPromotion["EndDate"],
    errors="coerce"
)

In [644]:
DimPromotion["CampaignName"] = (
    DimPromotion["CampaignName"]
        .str.strip()
        .str.title()
)

DimPromotion["PromotionType"] = (
    DimPromotion["PromotionType"]
        .str.strip()
        .str.title()
)

In [646]:
valid_types = [
    "Flat",
    "Percentage",
    "Cashback",
    "Free Shipping",
    "Bogo"
]

invalid_types = DimPromotion[
    ~DimPromotion["PromotionType"].isin(valid_types)
]

print(invalid_types)

Empty DataFrame
Columns: [PromotionID, CampaignName, DiscountPercent, StartDate, EndDate, PromotionType]
Index: []

In [648]:
Q1 = DimPromotion["DiscountPercent"].quantile(0.25)
Q3 = DimPromotion["DiscountPercent"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

DimPromotion[
    (DimPromotion["DiscountPercent"] < lower) |
    (DimPromotion["DiscountPercent"] > upper)
]

,PromotionID,CampaignName,DiscountPercent,StartDate,EndDate,PromotionType
10,11,Festive Campaign 11,95,2023-10-28,2023-11-27,Percentage
38,39,Mega Campaign 39,95,2023-08-19,2023-08-30,Free Shipping
86,87,Mega Campaign 87,95,2025-04-20,2025-05-11,Flat

In [650]:
invalid_dates = DimPromotion[
    DimPromotion["StartDate"] > DimPromotion["EndDate"]
]

print(invalid_dates)

    PromotionID          CampaignName  DiscountPercent  StartDate    EndDate  \
24           25  New Year Campaign 25               40 2024-09-02 2024-08-28
69           70   Premium Campaign 70               25 2023-06-11 2023-06-06

    PromotionType
24  Free Shipping
69  Free Shipping

In [652]:
mask = DimPromotion["StartDate"] > DimPromotion["EndDate"]

DimPromotion.loc[mask, ["StartDate", "EndDate"]] = (
    DimPromotion.loc[mask, ["EndDate", "StartDate"]].values
)

In [654]:
invalid_dates = DimPromotion[
    DimPromotion["StartDate"] > DimPromotion["EndDate"]
]

print(invalid_dates)

Empty DataFrame
Columns: [PromotionID, CampaignName, DiscountPercent, StartDate, EndDate, PromotionType]
Index: []

## DimSupplier_Enterprise

In [658]:
invalid_rating = DimSupplier_Enterprise[
    (DimSupplier_Enterprise["Rating"] < 1) |
    (DimSupplier_Enterprise["Rating"] > 5)
]

print(invalid_rating)

Empty DataFrame
Columns: [SupplierID, SupplierName, City, State, Rating, LeadTimeDays]
Index: []

In [664]:
valid_states = [
    "Andhra Pradesh",
    "Delhi",
    "Gujarat",
    "Karnataka",
    "Kerala",
    "Maharashtra",
    "Tamil Nadu",
    "Telangana",
    "Uttar Pradesh",
    "West Bengal"
]

invalid_state = DimSupplier_Enterprise[
    ~DimSupplier_Enterprise["State"].isin(valid_states)
]

print(invalid_state)

Empty DataFrame
Columns: [SupplierID, SupplierName, City, State, Rating, LeadTimeDays]
Index: []

In [662]:
valid_cities = [
    "Hyderabad",
    "Bengaluru",
    "Chennai",
    "Mumbai",
    "Pune",
    "Delhi",
    "Ahmedabad",
    "Kolkata"
]

invalid_city = DimSupplier_Enterprise[
    ~DimSupplier_Enterprise["City"].isin(valid_cities)
]

print(invalid_city)

Empty DataFrame
Columns: [SupplierID, SupplierName, City, State, Rating, LeadTimeDays]
Index: []

In [660]:
negative_leadtime = DimSupplier_Enterprise[
    DimSupplier_Enterprise["LeadTimeDays"] < 0
]

print(negative_leadtime)

    SupplierID            SupplierName       City      State  Rating  \
32          33  Global Distributors 34    Chennai  Telangana     4.2
90          91       Vertex Trading 92  Bengaluru  Karnataka     4.8

    LeadTimeDays
32            -4
90            -4

In [669]:
DimSupplier_Enterprise.loc[
    DimSupplier_Enterprise["LeadTimeDays"] < 0,
    "LeadTimeDays"
] = DimSupplier_Enterprise["LeadTimeDays"].median()

In [671]:
DimSupplier_Enterprise[
    DimSupplier_Enterprise["LeadTimeDays"] < 0
]

Empty DataFrame
Columns: [SupplierID, SupplierName, City, State, Rating, LeadTimeDays]
Index: []

## DimStore Enterprise

In [675]:
DimStore_Enterprise[
    DimStore_Enterprise["StoreName"].duplicated(keep=False)
].sort_values("StoreName")

,StoreID,StoreName,RegionID,StoreType,OpenDate,ManagerID
46,47,RetailHub Ahmedabad Branch,2,Outlet,2021-12-12,117
56,57,RetailHub Ahmedabad Branch,17,Mall,2023-04-27,446
16,17,RetailHub Ahmedabad Branch,6,Standalone,2020-02-12,394
23,24,RetailHub Delhi Branch,14,Outlet,2024-07-05,14
55,56,RetailHub Delhi Branch,24,Mall,2024-05-10,442
...,...,...,...,...,...,...
54,55,UrbanMart Kolkata Branch,3,Mall,2021-11-11,39
20,21,UrbanMart Kolkata Branch,2,Outlet,2023-03-22,402
71,72,UrbanMart Mumbai Branch,3,Mall,2018-01-17,314
22,23,UrbanMart Mumbai Branch,17,Standalone,2020-12-30,393
9,10,UrbanMart Mumbai Branch,2,Outlet,2018-10-19,386

In [678]:
DimStore_Enterprise["OpenDate"] = pd.to_datetime(
    DimStore_Enterprise["OpenDate"],
    errors="coerce"
)

In [680]:
DimStore_Enterprise["StoreName"] = (
    DimStore_Enterprise["StoreName"]
        .str.strip()
        .str.title()
)

DimStore_Enterprise["StoreType"] = (
    DimStore_Enterprise["StoreType"]
        .str.strip()
        .str.title()
)

In [682]:
valid_store_types = [
    "Mall",
    "Outlet",
    "Standalone"
]

invalid_storetype = DimStore_Enterprise[
    ~DimStore_Enterprise["StoreType"].isin(valid_store_types)
]

print(invalid_storetype)

Empty DataFrame
Columns: [StoreID, StoreName, RegionID, StoreType, OpenDate, ManagerID]
Index: []

In [684]:
future_store_dates = DimStore_Enterprise[
    DimStore_Enterprise["OpenDate"] > pd.Timestamp.today()
]

print(future_store_dates)

    StoreID                   StoreName  RegionID StoreType   OpenDate  \
7         8  Retailhub Hyderabad Branch         1      Mall 2028-05-01
43       44        Smartbuy Pune Branch        23    Outlet 2028-05-01

    ManagerID
7          48
43         86

In [686]:
median_date = DimStore_Enterprise["OpenDate"].median()

DimStore_Enterprise.loc[
    DimStore_Enterprise["OpenDate"] > pd.Timestamp.today(),
    "OpenDate"
] = median_date

In [688]:
future_store_dates = DimStore_Enterprise[
    DimStore_Enterprise["OpenDate"] > pd.Timestamp.today()
]

print(future_store_dates)

Empty DataFrame
Columns: [StoreID, StoreName, RegionID, StoreType, OpenDate, ManagerID]
Index: []

## DimEmployee Enterprise

In [691]:
DimEmployee_Enterprise[
    DimEmployee_Enterprise["EmployeeName"].duplicated(keep=False)
].sort_values("EmployeeName")

,EmployeeID,EmployeeName,Department,Designation,HireDate,Salary,StoreID,Status
104,105,Aarav Gupta,Marketing,Lead,2021-03-13,808936,1,Active
480,481,Aarav Gupta,Marketing,Manager,2024-11-09,458731,27,Active
254,255,Aarav Joshi,Finance,Executive,2020-04-13,736365,35,Active
171,172,Aarav Joshi,Operations,Executive,2021-03-11,749034,68,Active
389,390,Aarav Joshi,Sales,Manager,2022-01-26,505294,36,Inactive
...,...,...,...,...,...,...,...,...
66,67,Vivaan Singh,HR,Executive,2019-01-06,566624,99,Active
175,176,Vivaan Verma,IT,Executive,2021-05-27,1174316,38,Inactive
28,29,Vivaan Verma,Supply Chain,Manager,2024-10-31,384942,64,Active
264,265,Vivaan Verma,IT,Associate,2020-07-21,980972,42,Inactive
46,47,Vivaan Verma,Supply Chain,Lead,2021-11-17,298141,17,Inactive

In [693]:
DimEmployee_Enterprise["HireDate"] = pd.to_datetime(
    DimEmployee_Enterprise["HireDate"],
    errors="coerce"
)

In [695]:
text_columns = [
    "EmployeeName",
    "Department",
    "Designation",
    "Status"
]

for col in text_columns:
    DimEmployee_Enterprise[col] = (
        DimEmployee_Enterprise[col]
            .str.strip()
            .str.title()
    )

In [697]:
valid_departments = [
    "Finance",
    "Hr",
    "It",
    "Marketing",
    "Operations",
    "Sales",
    "Supply Chain"
]

invalid_department = DimEmployee_Enterprise[
    ~DimEmployee_Enterprise["Department"].isin(valid_departments)
]

print(invalid_department)

Empty DataFrame
Columns: [EmployeeID, EmployeeName, Department, Designation, HireDate, Salary, StoreID, Status]
Index: []

In [699]:
valid_designations = [
    "Analyst",
    "Associate",
    "Executive",
    "Lead",
    "Manager"
]

invalid_designation = DimEmployee_Enterprise[
    ~DimEmployee_Enterprise["Designation"].isin(valid_designations)
]

print(invalid_designation)

Empty DataFrame
Columns: [EmployeeID, EmployeeName, Department, Designation, HireDate, Salary, StoreID, Status]
Index: []

In [701]:
negative_salary = DimEmployee_Enterprise[
    DimEmployee_Enterprise["Salary"] < 0
]

print(negative_salary)

     EmployeeID EmployeeName  Department Designation   HireDate  Salary  \
20           21  Aarav Joshi          Hr     Analyst 2023-08-15 -450000
94           95   Aisha Nair  Operations   Associate 2020-10-15 -450000
187         188   Diya Joshi          It        Lead 2021-06-14 -450000

     StoreID    Status
20         2  Inactive
94        27  Inactive
187       64    Active

In [703]:
Q1 = DimEmployee_Enterprise["Salary"].quantile(0.25)
Q3 = DimEmployee_Enterprise["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

salary_outliers = DimEmployee_Enterprise[
    (DimEmployee_Enterprise["Salary"] < lower) |
    (DimEmployee_Enterprise["Salary"] > upper)
]

print(salary_outliers)

     EmployeeID EmployeeName  Department Designation   HireDate  Salary  \
20           21  Aarav Joshi          Hr     Analyst 2023-08-15 -450000
94           95   Aisha Nair  Operations   Associate 2020-10-15 -450000
187         188   Diya Joshi          It        Lead 2021-06-14 -450000

     StoreID    Status
20         2  Inactive
94        27  Inactive
187       64    Active

In [705]:
future_hires = DimEmployee_Enterprise[
    DimEmployee_Enterprise["HireDate"] > pd.Timestamp.today()
]

print(future_hires)

     EmployeeID   EmployeeName  Department Designation   HireDate  Salary  \
249         250  Ishaan Sharma  Operations     Manager 2028-01-01  279159
299         300     Kiran Nair  Operations   Associate 2028-01-01  865451

     StoreID  Status
249       40  Active
299       12  Active

In [707]:
median_salary = DimEmployee_Enterprise["Salary"].median()

DimEmployee_Enterprise.loc[
    DimEmployee_Enterprise["Salary"] < 0,
    "Salary"
] = median_salary

In [709]:
DimEmployee_Enterprise[
    DimEmployee_Enterprise["Salary"] < 0
]

Empty DataFrame
Columns: [EmployeeID, EmployeeName, Department, Designation, HireDate, Salary, StoreID, Status]
Index: []

In [711]:
median_hiredate = DimEmployee_Enterprise["HireDate"].median()

DimEmployee_Enterprise.loc[
    DimEmployee_Enterprise["HireDate"] > pd.Timestamp.today(),
    "HireDate"
] = median_hiredate

In [713]:
future_hires = DimEmployee_Enterprise[
    DimEmployee_Enterprise["HireDate"] > pd.Timestamp.today()
]

print(future_hires)

Empty DataFrame
Columns: [EmployeeID, EmployeeName, Department, Designation, HireDate, Salary, StoreID, Status]
Index: []

## DimDate

In [716]:
DimDate["FullDate"] = pd.to_datetime(
    DimDate["FullDate"],
    errors="coerce"
)

In [718]:
text_columns = [
    "MonthName",
    "DayName",
    "IsWeekend"
]

for col in text_columns:
    DimDate[col] = (
        DimDate[col]
            .str.strip()
            .str.title()
    )

In [720]:
valid_months = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

invalid_month = DimDate[
    ~DimDate["MonthName"].isin(valid_months)
]

print(invalid_month)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [722]:
valid_days = [
    "Monday","Tuesday","Wednesday",
    "Thursday","Friday","Saturday","Sunday"
]

invalid_day = DimDate[
    ~DimDate["DayName"].isin(valid_days)
]

print(invalid_day)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [724]:
valid_weekend = [
    "Yes",
    "No"
]

invalid_weekend = DimDate[
    ~DimDate["IsWeekend"].isin(valid_weekend)
]

print(invalid_weekend)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [726]:
invalid_month = DimDate[
    DimDate["Month"] != DimDate["FullDate"].dt.month
]

print(invalid_month)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [728]:
invalid_year = DimDate[
    DimDate["Year"] != DimDate["FullDate"].dt.year
]

print(invalid_year)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [730]:
invalid_day = DimDate[
    DimDate["Day"] != DimDate["FullDate"].dt.day
]

print(invalid_day)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [732]:
invalid_weekend_flag = DimDate[
    (
        DimDate["FullDate"].dt.dayofweek >= 5
    ) &
    (
        DimDate["IsWeekend"] != "Yes"
    )
]

print(invalid_weekend_flag)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

In [734]:
invalid_weekday_flag = DimDate[
    (
        DimDate["FullDate"].dt.dayofweek < 5
    ) &
    (
        DimDate["IsWeekend"] != "No"
    )
]

print(invalid_weekday_flag)

Empty DataFrame
Columns: [DateKey, FullDate, Day, Month, MonthName, Quarter, Year, Week, DayName, IsWeekend]
Index: []

## DimCustomer Enterprise

In [737]:
DimCustomer_Enterprise[
    DimCustomer_Enterprise["Email"].duplicated(keep=False)
].sort_values("Email")

,CustomerID,CustomerName,Gender,Age,City,State,RegionID,CustomerSegment,JoinDate,Email,Phone,Status
3119,3120,Aarav Kumar,Male,59,Mumbai,Telangana,14,Regular,2022-01-18,aarav.kumar100@gmail.com,9.784636e+09,Active
3058,3059,Aarav Kumar,Female,61,Chennai,Kerala,16,Regular,2023-05-25,aarav.kumar100@gmail.com,9.250705e+09,Active
2581,2582,Aarav Singh,Female,54,Hyderabad,Telangana,18,Regular,2021-07-28,aarav.singh691@gmail.com,9.599631e+09,Active
3779,3780,Aarav Singh,Female,61,Pune,Gujarat,10,Premium,2024-07-24,aarav.singh691@gmail.com,9.722247e+09,Active
2899,2900,Aditya Nair,Female,31,Delhi,Andhra Pradesh,16,Silver,2025-11-01,aditya.nair827@gmail.com,9.338249e+09,ACTIVE
...,...,...,...,...,...,...,...,...,...,...,...,...
65,66,Vivaan Sharma,Male,21,Bengaluru,Delhi,23,Silver,2020-05-24,vivaan.sharma322@gmail.com,9.165765e+09,Active
2023,2024,Vivaan Sharma,Male,40,Kolkata,Kerala,25,Gold,2022-05-05,vivaan.sharma737@gmail.com,9.911782e+09,Active
368,369,Vivaan Sharma,Male,30,Ahmedabad,Kerala,22,Regular,2024-10-25,vivaan.sharma737@gmail.com,NaN,Active
1219,1220,Vivaan Sharma,Female,21,Bengaluru,Delhi,18,Regular,2021-10-13,vivaan.sharma995@gmail.com,9.926645e+09,Active
3538,3539,Vivaan Sharma,Male,62,Mumbai,Uttar Pradesh,29,Premium,2023-10-04,vivaan.sharma995@gmail.com,9.387296e+09,Active

In [739]:
DimCustomer_Enterprise["JoinDate"] = pd.to_datetime(
    DimCustomer_Enterprise["JoinDate"],
    errors="coerce"
)

In [741]:
text_columns = [
    "CustomerName",
    "Gender",
    "City",
    "State",
    "CustomerSegment",
    "Status"
]

for col in text_columns:
    DimCustomer_Enterprise[col] = (
        DimCustomer_Enterprise[col]
            .str.strip()
            .str.title()
    )

In [743]:
DimCustomer_Enterprise["Gender"] = (
    DimCustomer_Enterprise["Gender"]
        .replace({
            "M": "Male",
            "F": "Female"
        })
)

In [745]:
mode_status = DimCustomer_Enterprise["Status"].mode()[0]

DimCustomer_Enterprise["Status"] = (
    DimCustomer_Enterprise["Status"]
        .fillna(mode_status)
)

In [747]:
DimCustomer_Enterprise["Phone"] = (
    DimCustomer_Enterprise["Phone"]
        .fillna("Not Available")
)

In [751]:
DimCustomer_Enterprise[
    (DimCustomer_Enterprise["Age"] < 18) |
    (DimCustomer_Enterprise["Age"] > 100)
]

,CustomerID,CustomerName,Gender,Age,City,State,RegionID,CustomerSegment,JoinDate,Email,Phone,Status
699,700,Vikram Kumar,Female,15,Bengaluru,Uttar Pradesh,13,Gold,2020-10-20,vikram.kumar843@gmail.com,9976262872.0,Active
700,701,Rohan Joshi,Male,15,Pune,Karnataka,16,Regular,2024-04-26,rohan.joshi580@gmail.com,9229068280.0,Active
701,702,Aisha Verma,Male,102,Chennai,Karnataka,8,Regular,2021-04-12,aisha.verma100@gmail.com,9227514130.0,Active

In [753]:
future_join = DimCustomer_Enterprise[
    DimCustomer_Enterprise["JoinDate"] > pd.Timestamp.today()
]

print(future_join)

      CustomerID  CustomerName  Gender  Age     City           State  \
999         1000  Rahul Sharma  Female   48  Chennai  Andhra Pradesh
1000        1001   Kiran Joshi    Male   40     Pune      Tamil Nadu

      RegionID CustomerSegment   JoinDate                      Email  \
999          6            Gold 2028-01-15  rahul.sharma709@gmail.com
1000         2            Gold 2028-01-15   kiran.joshi599@gmail.com

             Phone  Status
999   9099753591.0  Active
1000  9459469207.0  Active

In [757]:
median_age = DimCustomer_Enterprise["Age"].median()

DimCustomer_Enterprise.loc[
    (DimCustomer_Enterprise["Age"] < 18) |
    (DimCustomer_Enterprise["Age"] > 100),
    "Age"
] = median_age

In [759]:
DimCustomer_Enterprise[
    (DimCustomer_Enterprise["Age"] < 18) |
    (DimCustomer_Enterprise["Age"] > 100)
]

Empty DataFrame
Columns: [CustomerID, CustomerName, Gender, Age, City, State, RegionID, CustomerSegment, JoinDate, Email, Phone, Status]
Index: []

In [761]:
median_join = DimCustomer_Enterprise["JoinDate"].median()

DimCustomer_Enterprise.loc[
    DimCustomer_Enterprise["JoinDate"] > pd.Timestamp.today(),
    "JoinDate"
] = median_join

In [763]:
DimCustomer_Enterprise[
    DimCustomer_Enterprise["JoinDate"] > pd.Timestamp.today()
]

Empty DataFrame
Columns: [CustomerID, CustomerName, Gender, Age, City, State, RegionID, CustomerSegment, JoinDate, Email, Phone, Status]
Index: []

## DimProduct Enterprise

In [766]:
text_columns = [
    "ProductName",
    "Brand",
    "Status"
]

for col in text_columns:
    DimProduct_Enterprise[col] = (
        DimProduct_Enterprise[col]
            .str.strip()
            .str.title()
    )

In [768]:
mode_status = DimProduct_Enterprise["Status"].mode()[0]

DimProduct_Enterprise["Status"] = (
    DimProduct_Enterprise["Status"]
        .fillna(mode_status)
)

In [770]:
missing_category = DimProduct_Enterprise[
    DimProduct_Enterprise["CategoryID"].isna()
]

print(missing_category)

     ProductID             ProductName  CategoryID  SupplierID   Brand  \
499        500         Jbl Smart Watch         NaN         134     Jbl
500        501  Lenovo Inspiron Laptop         NaN          13  Lenovo
501        502    Dell Inspiron Laptop         NaN         119    Dell

     CostPrice  SellingPrice LaunchDate  Rating  Status
499    3914.69       4306.56 2023-10-22     4.2  Active
500   40116.71      61416.67 2023-05-14     5.8  Active
501   29414.01      42656.63 2022-12-14     3.5  Active

In [772]:
negative_price = DimProduct_Enterprise[
    DimProduct_Enterprise["SellingPrice"] < 0
]

print(negative_price)

     ProductID                       ProductName  CategoryID  SupplierID  \
79          80            Philips Vacuum Cleaner         4.0         162
251        252          Whirlpool Microwave Oven        13.0          70
254        255                    Cosco Yoga Mat         7.0         188
259        260  Acer Noise Cancelling Headphones        19.0           6
576        577                     Lakme Perfume         5.0         130
577        578                Durian Study Table         2.0         112
642        643             Mamaearth Body Lotion         5.0          90
645        646                    Amul Green Tea         6.0          70
828        829                    Amul Green Tea        15.0          98
848        849        Harpercollins Sql Cookbook         8.0          81

             Brand  CostPrice  SellingPrice LaunchDate  Rating  Status
79         Philips   33607.15     -50130.05 2021-01-02     4.0  Active
251      Whirlpool    3383.73      -5084.45 2021-04-29     3.5   Actve
254          Cosco   45849.02     -56714.21 2023-01-28     4.7  Active
259           Acer   23191.37     -27108.77 2024-01-04     3.7  Active
576          Lakme   28449.86     -34179.38 2021-11-29     3.3  Active
577         Durian   16308.62     -21436.41 2022-09-16     4.5  Active
642      Mamaearth   13596.54     -15491.16 2024-09-19     4.3  Active
645           Amul   38576.92     -46483.62 2024-01-17     4.0  Active
828           Amul   29793.39     -36303.34 2022-01-13     3.3  Active
848  Harpercollins    4092.83      -6197.84 2021-01-08     3.7  Active

In [774]:
invalid_price = DimProduct_Enterprise[
    DimProduct_Enterprise["SellingPrice"] <
    DimProduct_Enterprise["CostPrice"]
]

print(invalid_price)

     ProductID                           ProductName  CategoryID  SupplierID  \
29          30                  Hasbro Action Figure        18.0         166
79          80                Philips Vacuum Cleaner         4.0         162
99         100                         Nivea Perfume        14.0         131
100        101                     Amul Basmati Rice         6.0         109
132        133              Mcgraw Hill Sql Cookbook         8.0         199
208        209                         Nivea Perfume         5.0         152
251        252              Whirlpool Microwave Oven        13.0          70
254        255                        Cosco Yoga Mat         7.0         188
259        260      Acer Noise Cancelling Headphones        19.0           6
272        273                     Lakme Body Lotion        14.0          57
397        398                 Nilkamal Office Chair        11.0          82
540        541                Philips Vacuum Cleaner         4.0          82
546        547               Wilson Badminton Racket        16.0         143
567        568                Asus Bluetooth Speaker         1.0         170
576        577                         Lakme Perfume         5.0         130
577        578                    Durian Study Table         2.0         112
583        584                  Acer Inspiron Laptop        19.0         115
616        617                  Bosch Microwave Oven         4.0         128
642        643                 Mamaearth Body Lotion         5.0          90
645        646                        Amul Green Tea         6.0          70
670        671                        Lg Smart Watch        19.0         188
681        682                       Wilson Football        16.0          78
744        745             Hasbro Remote Control Car         9.0         166
802        803                         Lakme Shampoo         5.0         137
807        808  Mcgraw Hill Python For Data Analysis        17.0          30
824        825        Hp Noise Cancelling Headphones        19.0          22
828        829                        Amul Green Tea        15.0          98
835        836                         Ikea Wardrobe        11.0          18
848        849            Harpercollins Sql Cookbook         8.0          81
849        850                     Van Heusen Hoodie         3.0         151
865        866                 Havells Mixer Grinder        13.0         199
870        871                        Tata Green Tea         6.0         150
922        923                Apple Galaxy S24 Ultra         1.0         159
999       1000                    Maybelline Perfume        14.0         126

             Brand  CostPrice  SellingPrice LaunchDate  Rating  Status
29          Hasbro   17056.06      13644.85 2022-02-08     4.8  Active
79         Philips   33607.15     -50130.05 2021-01-02     4.0  Active
99           Nivea   47982.75      38386.20 2024-05-07     4.5  Active
100           Amul   48862.82      39090.26 2024-02-25     4.4  Active
132    Mcgraw Hill   33927.40      27141.92 2023-05-20     4.9  Active
208          Nivea   23362.04      18689.63 2024-08-12     4.8  Active
251      Whirlpool    3383.73      -5084.45 2021-04-29     3.5   Actve
254          Cosco   45849.02     -56714.21 2023-01-28     4.7  Active
259           Acer   23191.37     -27108.77 2024-01-04     3.7  Active
272          Lakme   42593.10      34074.48 2021-09-05     4.5  Active
397       Nilkamal   22232.86      17786.29 2025-07-01     3.9  Active
540        Philips    5802.38       4641.90 2024-05-22     3.3  Active
546         Wilson   13201.75      10561.40 2024-08-21     4.5  Active
567           Asus   51102.12      40881.70 2023-02-13     3.2   Actve
576          Lakme   28449.86     -34179.38 2021-11-29     3.3  Active
577         Durian   16308.62     -21436.41 2022-09-16     4.5  Active
583           Acer   54779.80      43823.84 2022-04-25     3.5  Active
616          Bosch   30746.83      24597.46 2025-06-19     3.5  Active
642      Mamaearth   13596.54     -15491.16 2024-09-19     4.3  Active
645           Amul   38576.92     -46483.62 2024-01-17     4.0  Active
670             Lg     612.67        490.14 2022-11-06     4.9  Active
681         Wilson   33783.68      27026.94 2025-10-21     3.3  Active
744         Hasbro   57213.59      45770.87 2023-03-21     4.0  Active
802          Lakme   22819.29      18255.43 2025-06-19     3.9  Active
807    Mcgraw Hill   51853.95      41483.16 2023-05-13     4.1  Active
824             Hp   24549.63      19639.70 2024-11-16     4.7  Active
828           Amul   29793.39     -36303.34 2022-01-13     3.3  Active
835           Ikea    1781.89       1425.51 2025-06-23     4.9  Active
848  Harpercollins    4092.83      -6197.84 2021-01-08     3.7  Active
849     Van Heusen   21325.83      17060.66 2021-05-27     4.7  Active
865        Havells   29468.00      23574.40 2028-03-01     3.6  Active
870           Tata   36435.03      29148.02 2022-06-26     4.0  Active
922          Apple   33873.40      27098.72 2025-08-27     4.5  Active
999     Maybelline   12072.08       9657.66 2025-06-11     4.1  Active

In [776]:
invalid_rating = DimProduct_Enterprise[
    (DimProduct_Enterprise["Rating"] < 1) |
    (DimProduct_Enterprise["Rating"] > 5)
]

print(invalid_rating)

     ProductID                ProductName  CategoryID  SupplierID  \
18          19              Ikea Wardrobe         2.0         146
35          36            Lego Puzzle Set        18.0          36
72          73       Aashirvaad Green Tea         6.0         129
96          97             Cosco Yoga Mat         7.0         154
183        184           Ifb Air Purifier         4.0           6
194        195  Allen Solly Running Shoes        12.0         149
304        305  Urban Ladder Dining Table        11.0         194
322        323          Amul Basmati Rice         6.0          84
387        388            Godrej Wardrobe         2.0          32
424        425             Cosco Football         7.0          32
471        472   Funskool Building Blocks         9.0         174
500        501     Lenovo Inspiron Laptop         NaN          13
555        556        Durian Coffee Table        20.0         108
704        705         Maybelline Perfume        14.0          95
713        714  Urban Ladder Office Chair        20.0          66

            Brand  CostPrice  SellingPrice LaunchDate  Rating  Status
18           Ikea   41588.52      62430.24 2024-07-06     0.0  Active
35           Lego   49327.13      74828.45 2022-06-25     5.8  Active
72     Aashirvaad   46723.69      55325.58 2024-04-29     0.0  Active
96          Cosco   28349.87      35924.19 2021-06-05     5.8  Active
183           Ifb   48159.42      53511.39 2025-08-20     0.0  Active
194   Allen Solly    3499.39       5081.08 2023-11-15     0.0  Active
304  Urban Ladder   51243.50      58314.51 2022-01-15     0.0  Active
322          Amul   14057.09      20512.23 2022-12-10     5.8  Active
387        Godrej   51215.55      80259.86 2021-10-06     0.0  Active
424         Cosco   20722.81      25499.40 2024-02-12     5.8  Active
471      Funskool   28164.14      39513.85 2024-01-31     5.8  Active
500        Lenovo   40116.71      61416.67 2023-05-14     5.8  Active
555        Durian   12628.86      17359.29 2025-08-12     0.0  Active
704    Maybelline   34833.88      47285.13 2024-03-11     5.8  Active
713  Urban Ladder   38671.53      60170.19 2025-10-29     0.0  Active

In [778]:
future_launch = DimProduct_Enterprise[
    DimProduct_Enterprise["LaunchDate"] >
    pd.Timestamp.today()
]

print(future_launch)

     ProductID               ProductName  CategoryID  SupplierID        Brand  \
45          46         Havells Air Fryer        13.0          83      Havells
52          53  Aashirvaad Organic Honey         6.0         137   Aashirvaad
64          65    Whirlpool Air Purifier        13.0         172    Whirlpool
148        149           Lakme Face Wash         5.0          90        Lakme
170        171              Sony Oled Tv        10.0         148         Sony
321        322            Cosco Yoga Mat        16.0          16        Cosco
359        360        Wilson Cricket Bat        16.0         153       Wilson
604        605  Mcgraw Hill Sql Cookbook        17.0          94  Mcgraw Hill
745        746      Penguin Sql Cookbook         8.0          73      Penguin
865        866     Havells Mixer Grinder        13.0         199      Havells
915        916            Yonex Football         7.0          29        Yonex
917        918      Nilkamal Study Table        20.0          57     Nilkamal

     CostPrice  SellingPrice LaunchDate  Rating  Status
45    28587.74      38566.50 2028-01-01     4.5  Active
52     4214.81       5533.39 2028-03-01     4.3  Active
64    30486.83      37361.37 2028-04-01     4.7  Active
148   21809.65      25628.24 2028-02-01     3.6  Active
170    8424.13      11426.06 2028-05-01     4.1  Active
321   12916.46      20345.61 2028-01-01     4.1  Active
359   15941.47      21235.84 2028-06-01     4.8  Active
604   14098.54      21379.39 2028-06-01     4.1  Active
745   46040.46      70965.83 2028-02-01     4.5  Active
865   29468.00      23574.40 2028-03-01     3.6  Active
915   25071.65      35759.29 2028-07-01     3.2  Active
917    1343.69       1491.64 2028-05-01     3.7  Active

In [780]:
valid_status = [
    "Active",
    "Inactive"
]

invalid_status = DimProduct_Enterprise[
    ~DimProduct_Enterprise["Status"].isin(valid_status)
]

print(invalid_status)

     ProductID                ProductName  CategoryID  SupplierID  \
210        211           Nestle Green Tea         6.0         138
251        252   Whirlpool Microwave Oven        13.0          70
263        264         Bosch Air Purifier        13.0         161
269        270     Maybelline Body Lotion        14.0          11
347        348    Lego Remote Control Car        18.0         195
390        391      Apple Inspiron Laptop        19.0          63
420        421         Lego Action Figure         9.0         189
421        422      Urban Ladder Wardrobe        20.0          35
567        568     Asus Bluetooth Speaker         1.0         170
772        773  Urban Ladder Office Chair        11.0          21
855        856                 Hp Oled Tv        10.0         178
893        894       Levi'S Running Shoes         3.0          90

            Brand  CostPrice  SellingPrice LaunchDate  Rating Status
210        Nestle   48662.15      74303.65 2024-01-04     3.2  Actve
251     Whirlpool    3383.73      -5084.45 2021-04-29     3.5  Actve
263         Bosch    4153.24       4805.64 2024-11-03     3.2  Actve
269    Maybelline    8453.60      12807.83 2024-05-15     4.8  Actve
347          Lego   29863.28      35789.15 2025-03-26     3.5  Actve
390         Apple   35655.52      56638.30 2022-01-01     4.6  Actve
420          Lego    7284.64      11058.52 2023-06-01     4.3  Actve
421  Urban Ladder   49065.76      56603.30 2021-02-02     3.3  Actve
567          Asus   51102.12      40881.70 2023-02-13     3.2  Actve
772  Urban Ladder   28132.61      32330.00 2021-06-22     4.0  Actve
855            Hp   49820.49      64760.25 2022-02-14     3.9  Actve
893        Levi'S   37194.49      50976.22 2024-04-25     4.4  Actve

In [782]:
DimProduct_Enterprise[
    DimProduct_Enterprise["CostPrice"] <= 0
]

Empty DataFrame
Columns: [ProductID, ProductName, CategoryID, SupplierID, Brand, CostPrice, SellingPrice, LaunchDate, Rating, Status]
Index: []

In [784]:
electronics_id = 1   # Use the actual CategoryID from DimCategory

DimProduct_Enterprise.loc[
    DimProduct_Enterprise["CategoryID"].isna(),
    "CategoryID"
] = electronics_id

In [786]:
median_price = DimProduct_Enterprise["SellingPrice"].median()

DimProduct_Enterprise.loc[
    DimProduct_Enterprise["SellingPrice"] < 0,
    "SellingPrice"
] = median_price

In [788]:
mask = (
    DimProduct_Enterprise["SellingPrice"] <
    DimProduct_Enterprise["CostPrice"]
)

DimProduct_Enterprise.loc[
    mask,
    "SellingPrice"
] = (
    DimProduct_Enterprise.loc[mask, "CostPrice"] * 1.20
)

In [790]:
median_rating = DimProduct_Enterprise["Rating"].median()

DimProduct_Enterprise.loc[
    (DimProduct_Enterprise["Rating"] < 1) |
    (DimProduct_Enterprise["Rating"] > 5),
    "Rating"
] = median_rating

In [792]:
median_launch = DimProduct_Enterprise["LaunchDate"].median()

DimProduct_Enterprise.loc[
    DimProduct_Enterprise["LaunchDate"] > pd.Timestamp.today(),
    "LaunchDate"
] = median_launch

In [794]:
DimProduct_Enterprise["Status"] = (
    DimProduct_Enterprise["Status"]
        .replace({
            "Actve": "Active"
        })
)

In [796]:
valid_status = ["Active", "Inactive"]

DimProduct_Enterprise[
    ~DimProduct_Enterprise["Status"].isin(valid_status)
]

Empty DataFrame
Columns: [ProductID, ProductName, CategoryID, SupplierID, Brand, CostPrice, SellingPrice, LaunchDate, Rating, Status]
Index: []

In [92]:
DimProduct_Enterprise["CategoryID"] = DimProduct_Enterprise["CategoryID"].fillna(0).astype(int)

In [798]:
dimension_tables = {
    "DimCategory": DimCategory,
    "DimRegion": DimRegion,
    "DimPromotion": DimPromotion,
    "DimSupplier_Enterprise": DimSupplier_Enterprise,
    "DimStore_Enterprise": DimStore_Enterprise,
    "DimEmployee_Enterprise": DimEmployee_Enterprise,product["CategoryID"] = product["CategoryID"].fillna(0).astype(int)
    "DimDate": DimDate,
    "DimCustomer_Enterprise": DimCustomer_Enterprise,
    "DimProduct_Enterprise": DimProduct_Enterprise
}

for table_name, df in dimension_tables.items():
    data_profiling_report(df, table_name)

====================================================================================================
DATA PROFILING REPORT : DimCategory
====================================================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------------------------------------
Rows               : 20
Columns            : 2
Memory Usage (KB)  : 1.41

2. COLUMN INFORMATION
----------------------------------------------------------------------------------------------------
               Column Name Data Type  Non Null Count
CategoryID      CategoryID     int64              20
CategoryName  CategoryName    object              20

3. MISSING VALUES
----------------------------------------------------------------------------------------------------
              Missing Count  Missing %
CategoryID                0        0.0
CategoryName              0        0.0

4. DUPLICATE ANALYSIS
----------------------------------------------------------------------------------------------------
Duplicate Rows : 0
Duplicate Primary Keys : 0

5. UNIQUE VALUES
----------------------------------------------------------------------------------------------------
              Unique Values
CategoryID               20
CategoryName             20

6. DESCRIPTIVE STATISTICS
----------------------------------------------------------------------------------------------------
        CategoryID CategoryName
count     20.00000           20
unique         NaN           20
top            NaN  Electronics
freq           NaN            1
mean      10.50000          NaN
std        5.91608          NaN
min        1.00000          NaN
25%        5.75000          NaN
50%       10.50000          NaN
75%       15.25000          NaN
max       20.00000          NaN

7. FREQUENCY DISTRIBUTION
----------------------------------------------------------------------------------------------------

Column : CategoryName
CategoryName
Electronics        1
Furniture          1
Stationery         1
Baby Products      1
Garden             1
Kitchen            1
Health             1
Office Supplies    1
Pet Supplies       1
Footwear           1
Jewelry            1
Automotive         1
Books              1
Toys               1
Beauty             1
Sports             1
Home Appliances    1
Grocery            1
Clothing           1
Music              1
Name: count, dtype: int64

8. DATE ANALYSIS
----------------------------------------------------------------------------------------------------
No Date Columns Found

9. OUTLIER DETECTION
----------------------------------------------------------------------------------------------------
CategoryID : 0 Outliers

10. INVALID VALUES
----------------------------------------------------------------------------------------------------
Blank Strings in Text Columns
CategoryName : 0

11. DATA CONSISTENCY
----------------------------------------------------------------------------------------------------
CategoryName
Original Unique : 20
After Standardization : 20


12. TEXT QUALITY
----------------------------------------------------------------------------------------------------

Column : CategoryName
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

13. DATA COMPLETENESS
----------------------------------------------------------------------------------------------------
              Complete %
CategoryID         100.0
CategoryName       100.0

Overall Dataset Completeness : 100.0%


====================================================================================================
END OF REPORT
====================================================================================================
====================================================================================================
DATA PROFILING REPORT : DimRegion
====================================================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------------------------------------
Rows               : 28
Columns            : 3
Memory Usage (KB)  : 3.41

2. COLUMN INFORMATION
----------------------------------------------------------------------------------------------------
           Column Name Data Type  Non Null Count
RegionID      RegionID     int64              28
RegionName  RegionName    object              28
Zone              Zone    object              28

3. MISSING VALUES
----------------------------------------------------------------------------------------------------
            Missing Count  Missing %
RegionID                0        0.0
RegionName              0        0.0
Zone                    0        0.0

4. DUPLICATE ANALYSIS
----------------------------------------------------------------------------------------------------
Duplicate Rows : 0
Duplicate Primary Keys : 0

5. UNIQUE VALUES
----------------------------------------------------------------------------------------------------
            Unique Values
RegionID               28
RegionName             28
Zone                    4

6. DESCRIPTIVE STATISTICS
----------------------------------------------------------------------------------------------------
         RegionID RegionName  Zone
count   28.000000         28    28
unique        NaN         28     4
top           NaN  Delhi Ncr  East
freq          NaN          1     8
mean    14.500000        NaN   NaN
std      8.225975        NaN   NaN
min      1.000000        NaN   NaN
25%      7.750000        NaN   NaN
50%     14.500000        NaN   NaN
75%     21.250000        NaN   NaN
max     28.000000        NaN   NaN

7. FREQUENCY DISTRIBUTION
----------------------------------------------------------------------------------------------------

Column : RegionName
Too many unique values (28). Top 10 shown below.
RegionName
Delhi Ncr         1
Punjab            1
Chhattisgarh      1
Madhya Pradesh    1
Rajasthan         1
Gujarat           1
Maharashtra       1
Tripura           1
Meghalaya         1
Sikkim            1
Name: count, dtype: int64

Column : Zone
Zone
East     8
North    7
South    7
West     6
Name: count, dtype: int64

8. DATE ANALYSIS
----------------------------------------------------------------------------------------------------
No Date Columns Found

9. OUTLIER DETECTION
----------------------------------------------------------------------------------------------------
RegionID : 0 Outliers

10. INVALID VALUES
----------------------------------------------------------------------------------------------------
Blank Strings in Text Columns
RegionName : 0
Zone : 0

11. DATA CONSISTENCY
----------------------------------------------------------------------------------------------------
RegionName
Original Unique : 28
After Standardization : 28

Zone
Original Unique : 4
After Standardization : 4


12. TEXT QUALITY
----------------------------------------------------------------------------------------------------

Column : RegionName
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

Column : Zone
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

13. DATA COMPLETENESS
----------------------------------------------------------------------------------------------------
            Complete %
RegionID         100.0
RegionName       100.0
Zone             100.0

Overall Dataset Completeness : 100.0%


====================================================================================================
END OF REPORT
====================================================================================================
====================================================================================================
DATA PROFILING REPORT : DimPromotion
====================================================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------------------------------------
Rows               : 150
Columns            : 6
Memory Usage (KB)  : 23.08

2. COLUMN INFORMATION
----------------------------------------------------------------------------------------------------
                     Column Name       Data Type  Non Null Count
PromotionID          PromotionID           int64             150
CampaignName        CampaignName          object             150
DiscountPercent  DiscountPercent           int64             150
StartDate              StartDate  datetime64[ns]             150
EndDate                  EndDate  datetime64[ns]             150
PromotionType      PromotionType          object             150

3. MISSING VALUES
----------------------------------------------------------------------------------------------------
                 Missing Count  Missing %
PromotionID                  0        0.0
CampaignName                 0        0.0
DiscountPercent              0        0.0
StartDate                    0        0.0
EndDate                      0        0.0
PromotionType                0        0.0

4. DUPLICATE ANALYSIS
----------------------------------------------------------------------------------------------------
Duplicate Rows : 0
Duplicate Primary Keys : 0

5. UNIQUE VALUES
----------------------------------------------------------------------------------------------------
                 Unique Values
PromotionID                150
CampaignName               149
DiscountPercent              9
StartDate                  144
EndDate                    142
PromotionType                5

6. DESCRIPTIVE STATISTICS
----------------------------------------------------------------------------------------------------
        PromotionID        CampaignName  DiscountPercent            StartDate  \
count    150.000000                 150       150.000000                  150
unique          NaN                 149              NaN                  NaN
top             NaN  Mega Festival Sale              NaN                  NaN
freq            NaN                   2              NaN                  NaN
mean      75.500000                 NaN        26.166667  2024-05-26 18:52:48
min        1.000000                 NaN         5.000000  2023-01-09 00:00:00
25%       38.250000                 NaN        15.000000  2023-09-29 00:00:00
50%       75.500000                 NaN        20.000000  2024-05-24 00:00:00
75%      112.750000                 NaN        40.000000  2025-01-13 18:00:00
max      150.000000                 NaN        95.000000  2025-09-26 00:00:00
std       43.445368                 NaN        17.207934                  NaN

                    EndDate PromotionType
count                   150           150
unique                  NaN             5
top                     NaN          Flat
freq                    NaN            33
mean    2024-06-21 07:50:24           NaN
min     2023-02-04 00:00:00           NaN
25%     2023-10-23 18:00:00           NaN
50%     2024-06-12 00:00:00           NaN
75%     2025-02-17 12:00:00           NaN
max     2025-10-14 00:00:00           NaN
std                     NaN           NaN

7. FREQUENCY DISTRIBUTION
----------------------------------------------------------------------------------------------------

Column : CampaignName
Too many unique values (149). Top 10 shown below.
CampaignName
Mega Festival Sale        2
Summer Campaign 1         1
Festive Campaign 96       1
Weekend Campaign 98       1
Premium Campaign 99       1
Summer Campaign 100       1
Clearance Campaign 101    1
Flash Campaign 102        1
Festive Campaign 103      1
Weekend Campaign 104      1
Name: count, dtype: int64

Column : PromotionType
PromotionType
Flat             33
Cashback         32
Percentage       30
Free Shipping    29
Bogo             26
Name: count, dtype: int64

8. DATE ANALYSIS
----------------------------------------------------------------------------------------------------

Column : StartDate
Minimum Date : 2023-01-09 00:00:00
Maximum Date : 2025-09-26 00:00:00
Missing Dates : 0

Column : EndDate
Minimum Date : 2023-02-04 00:00:00
Maximum Date : 2025-10-14 00:00:00
Missing Dates : 0

9. OUTLIER DETECTION
----------------------------------------------------------------------------------------------------
PromotionID : 0 Outliers
DiscountPercent : 3 Outliers

10. INVALID VALUES
----------------------------------------------------------------------------------------------------
Blank Strings in Text Columns
CampaignName : 0
PromotionType : 0

11. DATA CONSISTENCY
----------------------------------------------------------------------------------------------------
CampaignName
Original Unique : 149
After Standardization : 149

PromotionType
Original Unique : 5
After Standardization : 5


12. TEXT QUALITY
----------------------------------------------------------------------------------------------------

Column : CampaignName
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

Column : PromotionType
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

13. DATA COMPLETENESS
----------------------------------------------------------------------------------------------------
                 Complete %
PromotionID           100.0
CampaignName          100.0
DiscountPercent       100.0
StartDate             100.0
EndDate               100.0
PromotionType         100.0

Overall Dataset Completeness : 100.0%


====================================================================================================
END OF REPORT
====================================================================================================
====================================================================================================
DATA PROFILING REPORT : DimSupplier_Enterprise
====================================================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------------------------------------
Rows               : 200
Columns            : 6
Memory Usage (KB)  : 40.34

2. COLUMN INFORMATION
----------------------------------------------------------------------------------------------------
               Column Name Data Type  Non Null Count
SupplierID      SupplierID     int64             200
SupplierName  SupplierName    object             200
City                  City    object             200
State                State    object             200
Rating              Rating   float64             200
LeadTimeDays  LeadTimeDays     int64             200

3. MISSING VALUES
----------------------------------------------------------------------------------------------------
              Missing Count  Missing %
SupplierID                0        0.0
SupplierName              0        0.0
City                      0        0.0
State                     0        0.0
Rating                    0        0.0
LeadTimeDays              0        0.0

4. DUPLICATE ANALYSIS
----------------------------------------------------------------------------------------------------
Duplicate Rows : 0
Duplicate Primary Keys : 0

5. UNIQUE VALUES
----------------------------------------------------------------------------------------------------
              Unique Values
SupplierID              200
SupplierName            200
City                      8
State                    10
Rating                   19
LeadTimeDays             19

6. DESCRIPTIVE STATISTICS
----------------------------------------------------------------------------------------------------
        SupplierID      SupplierName       City   State      Rating  \
count   200.000000               200        200     200  200.000000
unique         NaN               200          8      10         NaN
top            NaN  Vertex Trading 2  Hyderabad  Kerala         NaN
freq           NaN                 1         33      26         NaN
mean    100.500000               NaN        NaN     NaN    4.161000
std      57.879185               NaN        NaN     NaN    0.527132
min       1.000000               NaN        NaN     NaN    3.200000
25%      50.750000               NaN        NaN     NaN    3.775000
50%     100.500000               NaN        NaN     NaN    4.200000
75%     150.250000               NaN        NaN     NaN    4.600000
max     200.000000               NaN        NaN     NaN    5.000000

        LeadTimeDays
count      200.00000
unique           NaN
top              NaN
freq             NaN
mean        11.46500
std          5.43567
min          2.00000
25%          7.00000
50%         12.00000
75%         16.00000
max         20.00000

7. FREQUENCY DISTRIBUTION
----------------------------------------------------------------------------------------------------

Column : SupplierName
Too many unique values (200). Top 10 shown below.
SupplierName
Vertex Trading 2           1
Prime Supply 139           1
TechSource 129             1
Global Distributors 130    1
Vertex Trading 131         1
Elite Imports 132          1
Apex Distribution 133      1
Prime Supply 134           1
Apex Distribution 135      1
BlueLine Supply 136        1
Name: count, dtype: int64

Column : City
City
Hyderabad    33
Chennai      27
Bengaluru    27
Kolkata      25
Ahmedabad    24
Pune         23
Mumbai       22
Delhi        19
Name: count, dtype: int64

Column : State
State
Kerala            26
Andhra Pradesh    25
West Bengal       23
Gujarat           22
Delhi             20
Telangana         19
Tamil Nadu        19
Uttar Pradesh     16
Maharashtra       16
Karnataka         14
Name: count, dtype: int64

8. DATE ANALYSIS
----------------------------------------------------------------------------------------------------
No Date Columns Found

9. OUTLIER DETECTION
----------------------------------------------------------------------------------------------------
SupplierID : 0 Outliers
Rating : 0 Outliers
LeadTimeDays : 0 Outliers

10. INVALID VALUES
----------------------------------------------------------------------------------------------------
Blank Strings in Text Columns
SupplierName : 0
City : 0
State : 0

11. DATA CONSISTENCY
----------------------------------------------------------------------------------------------------
SupplierName
Original Unique : 200
After Standardization : 200

City
Original Unique : 8
After Standardization : 8

State
Original Unique : 10
After Standardization : 10


12. TEXT QUALITY
----------------------------------------------------------------------------------------------------

Column : SupplierName
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

Column : City
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

Column : State
Leading Spaces : 0
Trailing Spaces : 0
Blank Values : 0

13. DATA COMPLETENESS
----------------------------------------------------------------------------------------------------
              Complete %
SupplierID         100.0
SupplierName       100.0
City               100.0
State              100.0
Rating             100.0
LeadTimeDays       100.0

Overall Dataset Completeness : 100.0%


====================================================================================================
END OF REPORT
====================================================================================================
====================================================================================================
DATA PROFILING REPORT : DimStore_Enterprise
====================================================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------------------------------------
Rows               : 80
Columns            : 6
Memory Usage (KB)  : 12.68

2. COLUMN INFORMATION
----------------------------------------------------------------------------------------------------
          Column Name       Data Type  Non Null Count

## FactOrders

In [801]:
invalid_customer = FactOrders[
    ~FactOrders["CustomerID"].isin(
        DimCustomer_Enterprise["CustomerID"]
    )
]

print(invalid_customer)

     OrderID  CustomerID  StoreID  PromotionID                  OrderDateKey  \
699      700      999999       19           77 1970-01-01 00:00:00.020261228
700      701      999999       10           91 1970-01-01 00:00:00.020261029

    OrderChannel OrderStatus  TotalAmount
699  Marketplace   Completed     20385.07
700       Online   Completed     57503.37

In [803]:
invalid_store = FactOrders[
    ~FactOrders["StoreID"].isin(
        DimStore_Enterprise["StoreID"]
    )
]

print(invalid_store)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [805]:
invalid_promotion = FactOrders[
    ~FactOrders["PromotionID"].isin(
        DimPromotion["PromotionID"]
    )
]

print(invalid_promotion)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [807]:
invalid_date = FactOrders[
    ~FactOrders["OrderDateKey"].isin(
        DimDate["DateKey"]
    )
]

print(invalid_date)

     OrderID  CustomerID  StoreID  PromotionID                  OrderDateKey  \
499      500        2405       33          128 1970-01-01 00:00:00.020280115
500      501         324       18           38 1970-01-01 00:00:00.020280115

    OrderChannel OrderStatus  TotalAmount
499      Offline   Completed     71008.99
500       Online   Completed     28458.55

In [809]:
negative_orders = FactOrders[
    FactOrders["TotalAmount"] < 0
]

print(negative_orders)

     OrderID  CustomerID  StoreID  PromotionID                  OrderDateKey  \
99       100        4680       18           61 1970-01-01 00:00:00.020241102
100      101        1981       28            7 1970-01-01 00:00:00.020230808
101      102        1582       67           66 1970-01-01 00:00:00.020240828
102      103        3627       80          142 1970-01-01 00:00:00.020261012
103      104        4979       79           56 1970-01-01 00:00:00.020230815
104      105        2575       36           29 1970-01-01 00:00:00.020260310
105      106        4327       71          106 1970-01-01 00:00:00.020251219
106      107        2131       69          124 1970-01-01 00:00:00.020230419
107      108        2006        5           18 1970-01-01 00:00:00.020230909
108      109        2297        3           81 1970-01-01 00:00:00.020250417
109      110        4144        7            8 1970-01-01 00:00:00.020260426

    OrderChannel OrderStatus  TotalAmount
99   Marketplace   Completed    -37168.20
100      Offline   Completed    -39461.98
101      Offline   Completed    -26893.92
102  Marketplace   Completed    -35685.16
103  Marketplace   Completed    -23596.07
104      Offline   Cancelled    -51451.99
105  Marketplace   Completed    -70489.39
106  Marketplace   Completed    -43963.65
107      Offline   Completed    -31927.57
108       Online   Cancelled     -1451.19
109  Marketplace   Completed    -67194.56

In [811]:
valid_channel = [
    "Online",
    "Offline",
    "Marketplace"
]

invalid_channel = FactOrders[
    ~FactOrders["OrderChannel"].isin(valid_channel)
]

print(invalid_channel)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [813]:
valid_status = [
    "Completed",
    "Pending",
    "Cancelled"
]

invalid_status = FactOrders[
    ~FactOrders["OrderStatus"].isin(valid_status)
]

print(invalid_status)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [815]:
text_columns = [
    "OrderChannel",
    "OrderStatus"
]

for col in text_columns:
    FactOrders[col] = (
        FactOrders[col]
        .str.strip()
        .str.title()
    )

In [817]:
FactOrders["OrderDateKey"] = (
    pd.to_datetime(
        FactOrders["OrderDateKey"].astype(str),
        format="%Y%m%d",
        errors="coerce"
    )
)

In [819]:
median_date = DimDate["FullDate"].median()

FactOrders.loc[
    FactOrders["OrderDateKey"] > pd.Timestamp.today(),
    "OrderDateKey"
] = median_date

In [821]:
FactOrders.loc[
    FactOrders["TotalAmount"] < 0,
    "TotalAmount"
] = (
    FactOrders.loc[
        FactOrders["TotalAmount"] < 0,
        "TotalAmount"
    ].abs()
)

In [823]:
FactOrders[
    FactOrders["TotalAmount"] < 0
]

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [825]:
FactOrders[
    ~FactOrders["CustomerID"].isin(
        DimCustomer_Enterprise["CustomerID"]
    )
]

,OrderID,CustomerID,StoreID,PromotionID,OrderDateKey,OrderChannel,OrderStatus,TotalAmount
699,700,999999,19,77,NaT,Marketplace,Completed,20385.07
700,701,999999,10,91,NaT,Online,Completed,57503.37

In [827]:
FactOrders[
    ~FactOrders["OrderDateKey"].isin(
        DimDate["DateKey"]
    )
]

,OrderID,CustomerID,StoreID,PromotionID,OrderDateKey,OrderChannel,OrderStatus,TotalAmount
0,1,4046,62,46,NaT,Marketplace,Pending,39139.47
1,2,4345,18,74,NaT,Marketplace,Completed,69463.58
2,3,3832,51,128,NaT,Online,Completed,2563.54
3,4,817,64,48,NaT,Online,Completed,1713.16
4,5,4712,14,101,NaT,Offline,Completed,65286.25
...,...,...,...,...,...,...,...,...
24995,24996,1116,15,137,NaT,Offline,Completed,34236.72
24996,24997,1775,40,148,NaT,Offline,Completed,5189.45
24997,24998,2115,14,113,NaT,Online,Completed,70498.55
24998,24999,1518,24,117,NaT,Online,Pending,41047.14
24999,25000,267,71,134,NaT,Marketplace,Cancelled,948.11

In [829]:
FactOrders[
    FactOrders["TotalAmount"] < 0
]

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

In [833]:
FactOrders = pd.read_excel(
    r"C:\Users\saisr\OneDrive\Pictures\Desktop\Final retail project\FactOrders.xlsx"
)

In [835]:
FactOrders["OrderDate"] = pd.to_datetime(
    FactOrders["OrderDateKey"].astype(str),
    format="%Y%m%d",
    errors="coerce"
)

In [837]:
FactOrders["OrderDate"] = pd.to_datetime(
    FactOrders["OrderDateKey"].astype(str),
    format="%Y%m%d",
    errors="coerce"
)

In [839]:
future_orders = FactOrders[
    FactOrders["OrderDate"] > pd.Timestamp.today()
]

In [841]:
median_date = DimDate["FullDate"].median()

FactOrders.loc[
    FactOrders["OrderDate"] > pd.Timestamp.today(),
    "OrderDate"
] = median_date

FactOrders["OrderDateKey"] = (
    FactOrders["OrderDate"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

In [849]:
invalid_date = FactOrders[
    ~FactOrders["OrderDateKey"].isin(DimDate["DateKey"])
]

print(invalid_date)

       OrderID  CustomerID  StoreID  PromotionID  OrderDateKey OrderChannel  \
0            1        4046       62           46      20231219  Marketplace
1            2        4345       18           74      20241014  Marketplace
2            3        3832       51          128      20251224       Online
3            4         817       64           48      20240204       Online
4            5        4712       14          101      20240805      Offline
...        ...         ...      ...          ...           ...          ...
24995    24996        1116       15          137      20230117      Offline
24996    24997        1775       40          148      20250127      Offline
24997    24998        2115       14          113      20250102       Online
24998    24999        1518       24          117      20250626       Online
24999    25000         267       71          134      20260130  Marketplace

      OrderStatus  TotalAmount
0         Pending     39139.47
1       Completed     69463.58
2       Completed      2563.54
3       Completed      1713.16
4       Completed     65286.25
...           ...          ...
24995   Completed     34236.72
24996   Completed      5189.45
24997   Completed     70498.55
24998     Pending     41047.14
24999   Cancelled       948.11

[25000 rows x 8 columns]

In [845]:
future_orders = FactOrders[
    FactOrders["OrderDate"] > pd.Timestamp.today()
]

print(future_orders)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount, OrderDate]
Index: []

In [847]:
FactOrders.drop(columns="OrderDate", inplace=True)

In [851]:
print(FactOrders["OrderDateKey"].dtype)
print(DimDate["DateKey"].dtype)

int32
datetime64[ns]

In [853]:
invalid_date = FactOrders[
    ~FactOrders["OrderDateKey"].isin(DimDate["DateKey"])
]

print(invalid_date)

       OrderID  CustomerID  StoreID  PromotionID  OrderDateKey OrderChannel  \
0            1        4046       62           46      20231219  Marketplace
1            2        4345       18           74      20241014  Marketplace
2            3        3832       51          128      20251224       Online
3            4         817       64           48      20240204       Online
4            5        4712       14          101      20240805      Offline
...        ...         ...      ...          ...           ...          ...
24995    24996        1116       15          137      20230117      Offline
24996    24997        1775       40          148      20250127      Offline
24997    24998        2115       14          113      20250102       Online
24998    24999        1518       24          117      20250626       Online
24999    25000         267       71          134      20260130  Marketplace

      OrderStatus  TotalAmount
0         Pending     39139.47
1       Completed     69463.58
2       Completed      2563.54
3       Completed      1713.16
4       Completed     65286.25
...           ...          ...
24995   Completed     34236.72
24996   Completed      5189.45
24997   Completed     70498.55
24998     Pending     41047.14
24999   Cancelled       948.11

[25000 rows x 8 columns]

In [855]:
DimDate["DateKey"] = (
    DimDate["FullDate"]
        .dt.strftime("%Y%m%d")
        .astype(int)
)

In [857]:
invalid_date = FactOrders[
    ~FactOrders["OrderDateKey"].isin(DimDate["DateKey"])
]

print(invalid_date)

Empty DataFrame
Columns: [OrderID, CustomerID, StoreID, PromotionID, OrderDateKey, OrderChannel, OrderStatus, TotalAmount]
Index: []

## FactOrderDetails

In [859]:
invalid_order = FactOrderDetails[
    ~FactOrderDetails["OrderID"].isin(FactOrders["OrderID"])
]

print(invalid_order)

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, Discount, Tax, LineTotal]
Index: []

In [861]:
invalid_product = FactOrderDetails[
    ~FactOrderDetails["ProductID"].isin(DimProduct_Enterprise["ProductID"])
]

print(invalid_product)

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, Discount, Tax, LineTotal]
Index: []

In [864]:
missing_tax = FactOrderDetails[
    FactOrderDetails["Tax"].isna()
]

print(missing_tax)

     OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  Tax  \
249            250       86        833         4   46203.81         0  NaN
250            251       86         48         4    7358.13        30  NaN
251            252       87        396         2   32954.43         5  NaN
252            253       87        231         4   34546.99        10  NaN
253            254       87        873         4   46217.34        20  NaN
..             ...      ...        ...       ...        ...       ...  ...
365            366      124        464         1   45705.41        10  NaN
366            367      124        589         4   24155.83        25  NaN
367            368      124        145         1     230.62        30  NaN
368            369      124        651         5   42677.98        30  NaN
369            370      125        568         4   10966.01        10  NaN

     LineTotal
249  218081.98
250   25900.61
251   74477.01
252  149242.99
253  181171.97
..         ...
365   49361.84
366   89859.69
367     202.94
368  187783.11
369   47373.17

[121 rows x 8 columns]

In [866]:
negative_qty = FactOrderDetails[
    FactOrderDetails["Quantity"] <= 0
]

print(negative_qty)

     OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  \
49              50       18        982         0    1653.38        30
50              51       19        671         0   32172.83        20
51              52       19        185         0    1886.77        10
52              53       19        965         0   12261.11        20
53              54       20        642         0   17920.99        20
54              55       20        638         0   11458.74        10
55              56       20        245         0   17625.47        25
56              57       21        563         0   23934.10        15
57              58       21        106         0   29772.59         5
58              59       21        784         0   23338.27        30
59              60       21        814         0   10129.25        10
60              61       22        564         0    8405.09        30
61              62       22        817         0   32423.14        20
62              63       22         68         0   27639.11         0
63              64       22        162         0   24162.11         5
64              65       23        238         0   31938.87        20
65              66       23        214         0   14085.97        30
66              67       23        911         0   10545.08        20
67              68       23        367         0    2719.23        15
68              69       24          4         0    4156.73        20
69              70       24        915         0   46283.73        20
70              71       24        490         0   20636.58        20
71              72       25         27         0   31948.40        20
72              73       25        313         0   38586.63        30
73              74       25        278         0   14176.31         5
74              75       25        392         0    1072.56        25
99             100       34        692        -2   17794.98         0
100            101       35        424        -2   35640.18         5
101            102       35        604        -2   20553.84         5
102            103       35        450        -2   10169.28        25
103            104       35        148        -2   23753.52        10
104            105       36         95        -2   42934.14         0
105            106       36        629        -2     758.05         5
106            107       36         58        -2    1716.48        20
107            108       36        206        -2    5544.02         5
108            109       37        581        -2    1616.64         0
109            110       37        664        -2   16534.02         0
110            111       37        844        -2   18585.27        10
111            112       37        163        -2    6098.48        25

          Tax  LineTotal
49     297.61    1454.98
50   11582.22   63058.75
51    1698.09   10188.56
52    6621.00   36047.66
53    3225.78   17562.57
54    6187.72   37126.32
55    3172.58   16391.68
56    4308.14   24652.12
57   21436.26  134572.10
58   12602.67   61613.04
59    7293.06   43758.36
60    7564.58   36982.39
61   23344.66  127098.71
62   24875.20  163070.75
63   13047.54   81909.55
64   17246.99   93900.28
65   12677.37   61978.26
66    1898.11   10334.17
67     978.92    5601.61
68    2992.85   16294.39
69    8331.07   45358.05
70   11143.75   60671.54
71    5750.71   31309.43
72   20836.78  101868.70
73    2551.74   16019.23
74     386.12    1994.96
99    3203.10   20998.08
100  32076.16  201367.01
101   3699.69   23225.84
102   5491.41   28372.29
103   4275.63   25653.80
104  30912.58  202649.14
105    136.45     856.60
106    617.93    3364.30
107   2993.77   18794.23
108    872.99    5722.91
109  11904.49   78040.57
110   3345.35   20072.09
111   4390.91   22686.35

In [868]:
valid_discount = [0,5,10,15,20,25,50,90]

invalid_discount = FactOrderDetails[
    ~FactOrderDetails["Discount"].isin(valid_discount)
]

print(invalid_discount)

       OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  \
6                  7        3        234         5   18853.13        30
15                16        6        669         1   27210.63        30
40                41       14        336         2   14199.73        30
44                45       16        643         1   21310.24        30
49                50       18        982         0    1653.38        30
...              ...      ...        ...       ...        ...       ...
75030          75031    24988        248         4    5739.74        30
75040          75041    24992        702         2   33005.68        30
75044          75045    24993        165         2   41778.99        30
75057          75058    24998        834         4   22138.46        30
75065          75066    25000        302         1   12274.28        30

            Tax  LineTotal
6      16967.82   82953.77
15      4897.91   23945.35
40      5111.90   24991.52
44      3835.84   18753.01
49       297.61    1454.98
...         ...        ...
75030   4132.61   20203.88
75040  11882.04   58089.99
75044  15040.44   73531.03
75057  15939.69   77927.38
75065   2209.37   10801.37

[10545 rows x 8 columns]

In [870]:
FactOrderDetails["CalculatedSubtotal"] = (
    FactOrderDetails["Quantity"]
    * FactOrderDetails["UnitPrice"]
)

In [872]:
negative_price = FactOrderDetails[
    FactOrderDetails["UnitPrice"] <= 0
]

print(negative_price)

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, Discount, Tax, LineTotal, CalculatedSubtotal]
Index: []

In [874]:
valid_discount = [
    0,
    5,
    10,
    15,
    20,
    25,
    30,
    50,
    90
]

In [876]:
median_qty = FactOrderDetails.loc[
    FactOrderDetails["Quantity"] > 0,
    "Quantity"
].median()

FactOrderDetails.loc[
    FactOrderDetails["Quantity"] <= 0,
    "Quantity"
] = median_qty

In [878]:
sample = FactOrderDetails[
    FactOrderDetails["Tax"].notna()
].copy()

sample["Subtotal"] = (
    sample["Quantity"]
    * sample["UnitPrice"]
)

sample["TaxRate"] = (
    sample["Tax"]
    / sample["Subtotal"]
)

sample["TaxRate"].describe()

count    74947.000000
mean         0.179990
std          0.001997
min          0.060000
25%          0.180000
50%          0.180000
75%          0.180000
max          0.300000
Name: TaxRate, dtype: float64

In [880]:
FactOrderDetails["ExpectedLineTotal"] = (
    (
        FactOrderDetails["Quantity"]
        * FactOrderDetails["UnitPrice"]
    )
    * (1 - FactOrderDetails["Discount"]/100)
    + FactOrderDetails["Tax"]
)

In [882]:
difference = FactOrderDetails[
    abs(
        FactOrderDetails["ExpectedLineTotal"]
        - FactOrderDetails["LineTotal"]
    ) > 1
]

print(difference)

     OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  \
49              50       18        982         3    1653.38        30
50              51       19        671         3   32172.83        20
51              52       19        185         3    1886.77        10
53              54       20        642         3   17920.99        20
55              56       20        245         3   17625.47        25
..             ...      ...        ...       ...        ...       ...
645            646      212        394         5   48499.50        20
646            647      212        231         3    6376.54        10
647            648      212        190         5   12480.32         0
648            649      212        746         3   21263.17        15
649            650      213        281         4   26846.27        30

          Tax  LineTotal  CalculatedSubtotal  ExpectedLineTotal
49     297.61    1454.98                0.00          3769.7080
50   11582.22   63058.75                0.00         88797.0120
51    1698.09   10188.56                0.00          6792.3690
53    3225.78   17562.57                0.00         46236.1560
55    3172.58   16391.68                0.00         42829.8875
..        ...        ...                 ...                ...
645  43649.55  238635.55           242497.50        237647.5500
646   3443.33   21651.99            19129.62         20659.9880
647  11232.29   74183.89            62401.60         73633.8900
648  11482.11   66198.19            63789.51         65703.1935
649  19329.31   95311.87           107385.08         94498.8660

[231 rows x 10 columns]

In [884]:
FactOrderDetails.loc[
    FactOrderDetails["Tax"].isna(),
    "Tax"
] = (
    FactOrderDetails.loc[
        FactOrderDetails["Tax"].isna(),
        "Quantity"
    ]
    *
    FactOrderDetails.loc[
        FactOrderDetails["Tax"].isna(),
        "UnitPrice"
    ]
    *
    0.18
)

In [886]:
FactOrderDetails["ExpectedLineTotal"] = (
    (
        FactOrderDetails["Quantity"]
        * FactOrderDetails["UnitPrice"]
    )
    * (1 - FactOrderDetails["Discount"] / 100)
    + FactOrderDetails["Tax"]
)

In [888]:
difference = FactOrderDetails[
    abs(
        FactOrderDetails["ExpectedLineTotal"]
        - FactOrderDetails["LineTotal"]
    ) > 1
]

print(difference)

     OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  \
49              50       18        982         3    1653.38        30
50              51       19        671         3   32172.83        20
51              52       19        185         3    1886.77        10
53              54       20        642         3   17920.99        20
55              56       20        245         3   17625.47        25
..             ...      ...        ...       ...        ...       ...
645            646      212        394         5   48499.50        20
646            647      212        231         3    6376.54        10
647            648      212        190         5   12480.32         0
648            649      212        746         3   21263.17        15
649            650      213        281         4   26846.27        30

          Tax  LineTotal  CalculatedSubtotal  ExpectedLineTotal
49     297.61    1454.98                0.00          3769.7080
50   11582.22   63058.75                0.00         88797.0120
51    1698.09   10188.56                0.00          6792.3690
53    3225.78   17562.57                0.00         46236.1560
55    3172.58   16391.68                0.00         42829.8875
..        ...        ...                 ...                ...
645  43649.55  238635.55           242497.50        237647.5500
646   3443.33   21651.99            19129.62         20659.9880
647  11232.29   74183.89            62401.60         73633.8900
648  11482.11   66198.19            63789.51         65703.1935
649  19329.31   95311.87           107385.08         94498.8660

[231 rows x 10 columns]

In [890]:
FactOrderDetails["CalculatedSubtotal"] = (
    FactOrderDetails["Quantity"]
    * FactOrderDetails["UnitPrice"]
)

In [892]:
mask = FactOrderDetails["OrderDetailID"].isin(negative_qty["OrderDetailID"])

FactOrderDetails.loc[mask, "Tax"] = (
    FactOrderDetails.loc[mask, "CalculatedSubtotal"] * 0.18
)

In [894]:
FactOrderDetails["ExpectedLineTotal"] = (
    FactOrderDetails["CalculatedSubtotal"]
    * (1 - FactOrderDetails["Discount"] / 100)
    + FactOrderDetails["Tax"]
)

In [896]:
difference = FactOrderDetails[
    abs(
        FactOrderDetails["ExpectedLineTotal"]
        - FactOrderDetails["LineTotal"]
    ) > 1
]

print(difference)

     OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount  \
49              50       18        982         3    1653.38        30
50              51       19        671         3   32172.83        20
51              52       19        185         3    1886.77        10
53              54       20        642         3   17920.99        20
55              56       20        245         3   17625.47        25
..             ...      ...        ...       ...        ...       ...
645            646      212        394         5   48499.50        20
646            647      212        231         3    6376.54        10
647            648      212        190         5   12480.32         0
648            649      212        746         3   21263.17        15
649            650      213        281         4   26846.27        30

            Tax  LineTotal  CalculatedSubtotal  ExpectedLineTotal
49     892.8252    1454.98             4960.14          4364.9232
50   17373.3282   63058.75            96518.49         94588.1202
51    1018.8558   10188.56             5660.31          6113.1348
53    9677.3346   17562.57            53762.97         52687.7106
55    9517.7538   16391.68            52876.41         49175.0613
..          ...        ...                 ...                ...
645  43649.5500  238635.55           242497.50        237647.5500
646   3443.3300   21651.99            19129.62         20659.9880
647  11232.2900   74183.89            62401.60         73633.8900
648  11482.1100   66198.19            63789.51         65703.1935
649  19329.3100   95311.87           107385.08         94498.8660

[231 rows x 10 columns]

In [898]:
sample = FactOrderDetails.iloc[49]

subtotal = sample["Quantity"] * sample["UnitPrice"]

discount_amt = subtotal * sample["Discount"] / 100

tax_before = subtotal * 0.18

tax_after = (subtotal - discount_amt) * 0.18

print("Subtotal :", subtotal)
print("Discount :", discount_amt)
print("Tax Before Discount :", tax_before)
print("Tax After Discount :", tax_after)
print("Stored Tax :", sample["Tax"])
print("Stored LineTotal :", sample["LineTotal"])

Subtotal : 4960.14
Discount : 1488.0420000000001
Tax Before Discount : 892.8252
Tax After Discount : 624.97764
Stored Tax : 892.8252
Stored LineTotal : 1454.98

In [902]:
mask = abs(
    FactOrderDetails["ExpectedLineTotal"] -
    FactOrderDetails["LineTotal"]
) > 1

FactOrderDetails.loc[
    mask,
    "LineTotal"
] = FactOrderDetails.loc[
    mask,
    "ExpectedLineTotal"
]

In [904]:
difference = FactOrderDetails[
    abs(
        FactOrderDetails["ExpectedLineTotal"]
        - FactOrderDetails["LineTotal"]
    ) > 1
]

print(difference)

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, Discount, Tax, LineTotal, CalculatedSubtotal, ExpectedLineTotal]
Index: []

In [906]:
difference = FactOrderDetails[
    abs(
        FactOrderDetails["ExpectedLineTotal"]
        - FactOrderDetails["LineTotal"]
    ) > 1
]

print(difference["Quantity"].value_counts())

Series([], Name: count, dtype: int64)

In [133]:
FactOrderDetails["Tax"] = FactOrderDetails["Tax"].fillna(0)

## FactPayments

In [911]:
invalid_order = FactPayments[
    ~FactPayments["OrderID"].isin(FactOrders["OrderID"])
]

print(invalid_order)

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount]
Index: []

In [913]:
valid_methods = [
    "Cash",
    "Credit Card",
    "Debit Card",
    "Net Banking",
    "UPI"
]

invalid_method = FactPayments[
    ~FactPayments["PaymentMethod"].isin(valid_methods)
]

print(invalid_method)

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount]
Index: []

In [915]:
valid_status = [
    "Success",
    "Pending",
    "Failed"
]

invalid_status = FactPayments[
    ~FactPayments["PaymentStatus"].isin(valid_status)
]

print(invalid_status)

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount]
Index: []

In [917]:
future_payment = FactPayments[
    FactPayments["PaymentDate"] > pd.Timestamp.today()
]

print(future_payment)

       PaymentID  OrderID PaymentMethod PaymentStatus PaymentDate  PaidAmount
16            17       17    Debit Card       Pending  2026-08-22    21160.02
19            20       20          Cash       Success  2026-09-09    32379.93
25            26       26           UPI       Success  2026-08-06    45211.28
27            28       28           UPI       Pending  2026-09-02    33390.79
62            63       63   Credit Card       Success  2026-11-09     4351.35
...          ...      ...           ...           ...         ...         ...
24970      24971    24971    Debit Card       Success  2026-11-03    29316.00
24975      24976    24976          Cash       Success  2026-09-12    14950.76
24979      24980    24980   Net Banking       Success  2026-10-26    43743.70
24981      24982    24982   Net Banking       Success  2026-12-25    15229.45
24993      24994    24994          Cash       Success  2026-11-22    73875.61

[2871 rows x 6 columns]

In [919]:
negative_payment = FactPayments[
    FactPayments["PaidAmount"] < 0
]

print(negative_payment)

     PaymentID  OrderID PaymentMethod PaymentStatus PaymentDate  PaidAmount
119        120      120           UPI        Failed  2026-03-14      -100.0
120        121      121   Net Banking       Success  2025-06-09      -100.0
121        122      122           UPI       Success  2025-05-23      -100.0
122        123      123   Credit Card       Success  2025-02-05      -100.0
123        124      124    Debit Card       Success  2026-08-07      -100.0
124        125      125           UPI       Success  2023-12-13      -100.0
125        126      126   Net Banking       Success  2026-11-10      -100.0
126        127      127   Credit Card       Pending  2023-06-08      -100.0
127        128      128   Credit Card       Success  2024-08-27      -100.0

In [921]:
payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

payment_check["Difference"] = (
    payment_check["PaidAmount"]
    - payment_check["TotalAmount"]
)

payment_check[
    abs(payment_check["Difference"]) > 1
]

,PaymentID,OrderID,PaymentMethod,PaymentStatus,PaymentDate,PaidAmount,TotalAmount,Difference
99,100,100,UPI,Success,2024-11-03,0.00,-37168.20,37168.20
100,101,101,Net Banking,Success,2023-08-09,0.00,-39461.98,39461.98
101,102,102,Cash,Success,2024-08-28,0.00,-26893.92,26893.92
102,103,103,Credit Card,Success,2026-10-12,0.00,-35685.16,35685.16
103,104,104,Credit Card,Success,2023-08-16,0.00,-23596.07,23596.07
104,105,105,Cash,Failed,2026-03-12,0.00,-51451.99,51451.99
105,106,106,Cash,Success,2025-12-20,0.00,-70489.39,70489.39
106,107,107,Cash,Success,2023-04-21,0.00,-43963.65,43963.65
107,108,108,Debit Card,Success,2023-09-11,0.00,-31927.57,31927.57
108,109,109,UPI,Success,2025-04-17,0.00,-1451.19,1451.19
109,110,110,Credit Card,Success,2026-04-26,0.00,-67194.56,67194.56
119,120,120,UPI,Failed,2026-03-14,-100.00,48300.22,-48400.22
120,121,121,Net Banking,Success,2025-06-09,-100.00,11830.33,-11930.33
121,122,122,UPI,Success,2025-05-23,-100.00,65050.86,-65150.86
122,123,123,Credit Card,Success,2025-02-05,-100.00,5588.19,-5688.19
123,124,124,Debit Card,Success,2026-08-07,-100.00,70901.83,-71001.83
124,125,125,UPI,Success,2023-12-13,-100.00,2591.36,-2691.36
125,126,126,Net Banking,Success,2026-11-10,-100.00,4501.46,-4601.46
126,127,127,Credit Card,Pending,2023-06-08,-100.00,1713.64,-1813.64
127,128,128,Credit Card,Success,2024-08-27,-100.00,52014.60,-52114.60
299,300,300,UPI,Success,2024-01-09,67932.21,67432.21,500.00
300,301,301,Cash,Success,2026-09-15,20612.19,20112.19,500.00

In [923]:
median_payment_date = FactPayments["PaymentDate"].median()

FactPayments.loc[
    FactPayments["PaymentDate"] > pd.Timestamp.today(),
    "PaymentDate"
] = median_payment_date

In [925]:
FactPayments[
    FactPayments["PaymentDate"] > pd.Timestamp.today()
]

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount]
Index: []

In [927]:
FactPayments = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

FactPayments.loc[
    FactPayments["PaidAmount"] < 0,
    "PaidAmount"
] = FactPayments.loc[
    FactPayments["PaidAmount"] < 0,
    "TotalAmount"
]

FactPayments.drop(columns="TotalAmount", inplace=True)

In [929]:
FactPayments[
    FactPayments["PaidAmount"] < 0
]

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount]
Index: []

In [931]:
payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

payment_check["Difference"] = (
    payment_check["PaidAmount"]
    - payment_check["TotalAmount"]
)

payment_check[
    abs(payment_check["Difference"]) > 1
]

,PaymentID,OrderID,PaymentMethod,PaymentStatus,PaymentDate,PaidAmount,TotalAmount,Difference
99,100,100,UPI,Success,2024-11-03,0.00,-37168.20,37168.20
100,101,101,Net Banking,Success,2023-08-09,0.00,-39461.98,39461.98
101,102,102,Cash,Success,2024-08-28,0.00,-26893.92,26893.92
102,103,103,Credit Card,Success,2024-12-29,0.00,-35685.16,35685.16
103,104,104,Credit Card,Success,2023-08-16,0.00,-23596.07,23596.07
104,105,105,Cash,Failed,2026-03-12,0.00,-51451.99,51451.99
105,106,106,Cash,Success,2025-12-20,0.00,-70489.39,70489.39
106,107,107,Cash,Success,2023-04-21,0.00,-43963.65,43963.65
107,108,108,Debit Card,Success,2023-09-11,0.00,-31927.57,31927.57
108,109,109,UPI,Success,2025-04-17,0.00,-1451.19,1451.19
109,110,110,Credit Card,Success,2026-04-26,0.00,-67194.56,67194.56
299,300,300,UPI,Success,2024-01-09,67932.21,67432.21,500.00
300,301,301,Cash,Success,2024-12-29,20612.19,20112.19,500.00

In [936]:
payment_check[
    payment_check["PaidAmount"] == 0
]

,PaymentID,OrderID,PaymentMethod,PaymentStatus,PaymentDate,PaidAmount,TotalAmount,Difference
99,100,100,UPI,Success,2024-11-03,0.0,-37168.20,37168.20
100,101,101,Net Banking,Success,2023-08-09,0.0,-39461.98,39461.98
101,102,102,Cash,Success,2024-08-28,0.0,-26893.92,26893.92
102,103,103,Credit Card,Success,2024-12-29,0.0,-35685.16,35685.16
103,104,104,Credit Card,Success,2023-08-16,0.0,-23596.07,23596.07
104,105,105,Cash,Failed,2026-03-12,0.0,-51451.99,51451.99
105,106,106,Cash,Success,2025-12-20,0.0,-70489.39,70489.39
106,107,107,Cash,Success,2023-04-21,0.0,-43963.65,43963.65
107,108,108,Debit Card,Success,2023-09-11,0.0,-31927.57,31927.57
108,109,109,UPI,Success,2025-04-17,0.0,-1451.19,1451.19
109,110,110,Credit Card,Success,2026-04-26,0.0,-67194.56,67194.56

In [938]:
FactOrders[
    FactOrders["OrderID"].between(100,110)
][["OrderID","TotalAmount"]]

     OrderID  TotalAmount
99       100    -37168.20
100      101    -39461.98
101      102    -26893.92
102      103    -35685.16
103      104    -23596.07
104      105    -51451.99
105      106    -70489.39
106      107    -43963.65
107      108    -31927.57
108      109     -1451.19
109      110    -67194.56

In [940]:
FactOrders.loc[
    FactOrders["TotalAmount"] < 0,
    "TotalAmount"
] = (
    FactOrders.loc[
        FactOrders["TotalAmount"] < 0,
        "TotalAmount"
    ].abs()
)

In [942]:
FactOrders[
    FactOrders["OrderID"].between(100,110)
][["OrderID","TotalAmount"]]

     OrderID  TotalAmount
99       100     37168.20
100      101     39461.98
101      102     26893.92
102      103     35685.16
103      104     23596.07
104      105     51451.99
105      106     70489.39
106      107     43963.65
107      108     31927.57
108      109      1451.19
109      110     67194.56

In [944]:
payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

payment_check["Difference"] = (
    payment_check["PaidAmount"]
    - payment_check["TotalAmount"]
)

In [946]:
payment_check[
    abs(payment_check["Difference"]) > 1
]

,PaymentID,OrderID,PaymentMethod,PaymentStatus,PaymentDate,PaidAmount,TotalAmount,Difference
99,100,100,UPI,Success,2024-11-03,0.00,37168.20,-37168.20
100,101,101,Net Banking,Success,2023-08-09,0.00,39461.98,-39461.98
101,102,102,Cash,Success,2024-08-28,0.00,26893.92,-26893.92
102,103,103,Credit Card,Success,2024-12-29,0.00,35685.16,-35685.16
103,104,104,Credit Card,Success,2023-08-16,0.00,23596.07,-23596.07
104,105,105,Cash,Failed,2026-03-12,0.00,51451.99,-51451.99
105,106,106,Cash,Success,2025-12-20,0.00,70489.39,-70489.39
106,107,107,Cash,Success,2023-04-21,0.00,43963.65,-43963.65
107,108,108,Debit Card,Success,2023-09-11,0.00,31927.57,-31927.57
108,109,109,UPI,Success,2025-04-17,0.00,1451.19,-1451.19
109,110,110,Credit Card,Success,2026-04-26,0.00,67194.56,-67194.56
299,300,300,UPI,Success,2024-01-09,67932.21,67432.21,500.00
300,301,301,Cash,Success,2024-12-29,20612.19,20112.19,500.00

In [948]:
mask = FactPayments["PaidAmount"] == 0

payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

FactPayments.loc[
    mask,
    "PaidAmount"
] = payment_check.loc[
    mask,
    "TotalAmount"
]

In [950]:
payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

payment_check["Difference"] = (
    payment_check["PaidAmount"]
    - payment_check["TotalAmount"]
)

payment_check[
    abs(payment_check["Difference"]) > 1
]

,PaymentID,OrderID,PaymentMethod,PaymentStatus,PaymentDate,PaidAmount,TotalAmount,Difference
299,300,300,UPI,Success,2024-01-09,67932.21,67432.21,500.0
300,301,301,Cash,Success,2024-12-29,20612.19,20112.19,500.0

In [952]:
mask = abs(payment_check["Difference"]) > 1

FactPayments.loc[
    FactPayments["OrderID"].isin(
        payment_check.loc[mask, "OrderID"]
    ),
    "PaidAmount"
] = payment_check.loc[
    mask,
    "TotalAmount"
].values

In [954]:
payment_check = FactPayments.merge(
    FactOrders[["OrderID", "TotalAmount"]],
    on="OrderID",
    how="left"
)

payment_check["Difference"] = (
    payment_check["PaidAmount"]
    - payment_check["TotalAmount"]
)

payment_check[
    abs(payment_check["Difference"]) > 1
]

Empty DataFrame
Columns: [PaymentID, OrderID, PaymentMethod, PaymentStatus, PaymentDate, PaidAmount, TotalAmount, Difference]
Index: []

## FactReturns

In [959]:
invalid_order = FactReturns[
    ~FactReturns["OrderID"].isin(FactOrders["OrderID"])
]

print(invalid_order)

    ReturnID  OrderID  ProductID   ReturnReason ReturnDate  RefundAmount
29        30   999999        312  Late Delivery 2023-02-22      22100.56
30        31   999999        803     Wrong Item 2024-02-05      14026.32
31        32   999999        235  Missing Parts 2025-06-04       2417.44
32        33   999999         44     Wrong Item 2024-12-11      15442.94
33        34   999999        423     Wrong Item 2024-12-13        992.52
34        35   999999        150  Missing Parts 2026-06-12       8619.86
35        36   999999        539  Late Delivery 2025-05-08       7673.37
36        37   999999        626   Changed Mind 2023-06-22      24970.57
37        38   999999        216      Defective 2026-12-13      18896.99
38        39   999999        123      Defective 2023-03-09       3982.28
39        40   999999        704  Late Delivery 2025-09-04       9061.74
40        41   999999        845  Late Delivery 2025-04-25        331.86
41        42   999999        360   Changed Mind 2025-05-20      18879.93

In [961]:
invalid_product = FactReturns[
    ~FactReturns["ProductID"].isin(
        DimProduct_Enterprise["ProductID"]
    )
]

print(invalid_product)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount]
Index: []

In [963]:
valid_reasons = [
    "Defective",
    "Damaged",
    "Missing Parts",
    "Late Delivery",
    "Wrong Item",
    "Changed Mind"
]

invalid_reason = FactReturns[
    ~FactReturns["ReturnReason"].isin(valid_reasons)
]

print(invalid_reason)

     ReturnID  OrderID  ProductID ReturnReason ReturnDate  RefundAmount
149       150     2527        780      Unknown 2025-10-16       9813.65
150       151     5189        177      Unknown 2023-08-01       6517.42
151       152    11520        254      Unknown 2025-05-11      10875.32
152       153    13912        956      Unknown 2025-02-20      11283.01
153       154     8533          7      Unknown 2024-12-08      22685.96
154       155     1257        597      Unknown 2023-10-12      20606.96
155       156    15508        351      Unknown 2024-11-23      14112.62
156       157    12725        608      Unknown 2024-08-07       2636.48
157       158    21489        645      Unknown 2025-10-17      20618.25
158       159     9086        934      Unknown 2023-07-27        664.46
159       160      771        974      Unknown 2024-03-24       9901.41
160       161    15842        483      Unknown 2026-11-28      12715.63
161       162    13075        856      Unknown 2023-02-06       5105.18
162       163     9131        505      Unknown 2024-10-14      19278.54
163       164    18776        943      Unknown 2023-01-29      21271.65
164       165    21532        295      Unknown 2026-07-28      24443.64
165       166     5024        551      Unknown 2024-05-14       4888.98
166       167     7235        372      Unknown 2026-09-02        406.98
167       168     3951        386      Unknown 2025-08-30      15964.82
168       169    22167        844      Unknown 2023-10-04      16233.65
169       170      580        655      Unknown 2023-12-12      10634.13

In [965]:
future_returns = FactReturns[
    FactReturns["ReturnDate"] > pd.Timestamp.today()
]

print(future_returns)

      ReturnID  OrderID  ProductID  ReturnReason ReturnDate  RefundAmount
4            5    20681        331     Defective 2027-01-18       2696.34
19          20    23401        766     Defective 2026-10-30       4210.48
25          26    11957         78       Damaged 2026-08-04      21747.67
28          29     6456          4  Changed Mind 2027-01-07      17763.05
37          38   999999        216     Defective 2026-12-13      18896.99
...        ...      ...        ...           ...        ...           ...
3463      3464     9270        779       Damaged 2026-11-18       7630.23
3475      3476     4424        436    Wrong Item 2026-12-28       1517.85
3486      3487     8921        855     Defective 2026-10-09      10422.29
3498      3499    22206        156    Wrong Item 2026-08-16      17166.34
3499      3500    10204        785       Damaged 2026-08-06       2324.35

[444 rows x 6 columns]

In [967]:
negative_refund = FactReturns[
    FactReturns["RefundAmount"] < 0
]

print(negative_refund)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount]
Index: []

In [969]:
return_check = FactReturns.merge(
    FactOrders[
        ["OrderID", "TotalAmount"]
    ],
    on="OrderID",
    how="left"
)

invalid_refund = return_check[
    return_check["RefundAmount"] >
    return_check["TotalAmount"]
]

print(invalid_refund)

      ReturnID  OrderID  ProductID   ReturnReason ReturnDate  RefundAmount  \
1            2    18473        936        Damaged 2025-01-22      20509.93
10          11    18369         86      Defective 2025-04-10       5233.07
12          13    19878        424        Damaged 2023-04-14      24452.15
13          14     6914        615  Missing Parts 2025-01-12      21846.33
20          21    17467        328        Damaged 2026-05-29       8511.41
...        ...      ...        ...            ...        ...           ...
3477      3478    20658        638  Missing Parts 2026-01-21      23807.00
3479      3480     8089        178      Defective 2023-08-26      13287.10
3483      3484    12900        883  Late Delivery 2024-04-22      16812.82
3484      3485     5421        910        Damaged 2023-09-23      23400.22
3487      3488    16545        999  Late Delivery 2024-09-06       7203.02

      TotalAmount
1        12225.82
10         410.07
12       12259.03
13       11822.25
20        1553.11
...           ...
3477     12099.70
3479     10415.91
3483     10372.12
3484     21542.72
3487      4472.09

[580 rows x 7 columns]

In [971]:
FactReturns["ReturnReason"] = (
    FactReturns["ReturnReason"]
    .str.strip()
    .str.title()
)

In [973]:
valid_orders = FactOrders["OrderID"].sample(
    13,
    random_state=42
).values

FactReturns.loc[
    FactReturns["OrderID"] == 999999,
    "OrderID"
] = valid_orders

In [975]:
invalid_order = FactReturns[
    ~FactReturns["OrderID"].isin(FactOrders["OrderID"])
]

print(invalid_order)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount]
Index: []

In [977]:
mode_reason = FactReturns["ReturnReason"].mode()[0]

FactReturns.loc[
    FactReturns["ReturnReason"] == "Unknown",
    "ReturnReason"
] = mode_reason

In [979]:
invalid_reason = FactReturns[
    ~FactReturns["ReturnReason"].isin(valid_reasons)
]

print(invalid_reason)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount]
Index: []

In [981]:
median_return = FactReturns["ReturnDate"].median()

FactReturns.loc[
    FactReturns["ReturnDate"] > pd.Timestamp.today(),
    "ReturnDate"
] = median_return

In [983]:
future_returns = FactReturns[
    FactReturns["ReturnDate"] > pd.Timestamp.today()
]

print(future_returns)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount]
Index: []

In [985]:
return_check = FactReturns.merge(
    FactOrders[
        ["OrderID", "TotalAmount"]
    ],
    on="OrderID",
    how="left"
)

mask = (
    return_check["RefundAmount"] >
    return_check["TotalAmount"]
)

FactReturns.loc[
    mask,
    "RefundAmount"
] = return_check.loc[
    mask,
    "TotalAmount"
].values

In [987]:
return_check = FactReturns.merge(
    FactOrders[
        ["OrderID", "TotalAmount"]
    ],
    on="OrderID",
    how="left"
)

invalid_refund = return_check[
    return_check["RefundAmount"] >
    return_check["TotalAmount"]
]

print(invalid_refund)

Empty DataFrame
Columns: [ReturnID, OrderID, ProductID, ReturnReason, ReturnDate, RefundAmount, TotalAmount]
Index: []

In [989]:
return_check[
    return_check["RefundAmount"] >
    return_check["TotalAmount"]
][
    [
        "OrderID",
        "RefundAmount",
        "TotalAmount"
    ]
].head(10)

Empty DataFrame
Columns: [OrderID, RefundAmount, TotalAmount]
Index: []

## FactInventory

In [992]:
FactInventory["LastRestocked"] = pd.to_datetime(
    FactInventory["LastRestocked"],
    errors="coerce"
)

In [994]:
invalid_product = FactInventory[
    ~FactInventory["ProductID"].isin(
        DimProduct_Enterprise["ProductID"]
    )
]

print(invalid_product)

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [996]:
invalid_store = FactInventory[
    ~FactInventory["StoreID"].isin(
        DimStore_Enterprise["StoreID"]
    )
]

print(invalid_store)

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [998]:
missing_date = FactInventory[
    FactInventory["LastRestocked"].isna()
]

print(missing_date)

     InventoryID  ProductID  StoreID  StockAvailable  ReorderLevel  \
299          300        367       36             174            72
300          301        672       47             306           105
301          302         90       52             437            21
302          303        234       58              49            56
303          304        419       79             365            51
304          305        649       66             587           131
305          306        442       15             345            63
306          307        355       59             145           135
307          308        587       77             730            93
308          309        370       67             326            73
309          310         37       77             728           104
310          311        802       11             100            58
311          312        181       45             303           102
312          313        970       44             406           123
313          314        250       75             549           122
314          315        263       28             207           136
315          316        351       30               5           139
316          317        709       80             655           117
317          318         90       17             112           107
318          319        605       60             454            67
319          320        657       56              34           103
320          321        481       12             302            39
321          322        392        8             772            29
322          323        146       14             615            44
323          324        351       72             221            83
324          325        827       14             608           116
325          326        853       51             722            26
326          327        723       10             532            49
327          328        906       26             592           134
328          329        404       11             424            58
329          330        401       21             726           111
330          331        528       77             457            36
331          332        506       23              84           138
332          333        710       79             780            47
333          334        419       52             687           129
334          335        832        5             208            77
335          336        308       56             637           113
336          337        236       42              67           143
337          338        754       40             227            95
338          339        978        4             642           125
339          340        472       74              65           118
340          341        680       80              57           148
341          342        970       39             697            41
342          343        257       17             613           148
343          344        640        5             478            60
344          345        402       29             775           103
345          346         34       12             306            97
346          347        388       26             776           136
347          348        446       68             599            62
348          349         70       54             794            61
349          350        610       22             292           135

    LastRestocked
299           NaT
300           NaT
301           NaT
302           NaT
303           NaT
304           NaT
305           NaT
306           NaT
307           NaT
308           NaT
309           NaT
310           NaT
311           NaT
312           NaT
313           NaT
314           NaT
315           NaT
316           NaT
317           NaT
318           NaT
319           NaT
320           NaT
321           NaT
322           NaT
323           NaT
324           NaT
325           NaT
326           NaT
327           NaT
328           NaT
329           NaT
330           NaT
331           NaT
332           NaT
333           NaT
334           NaT
335           NaT
336           NaT
337           NaT
338           NaT
339           NaT
340           NaT
341           NaT
342           NaT
343           NaT
344           NaT
345           NaT
346           NaT
347           NaT
348           NaT
349           NaT

In [1000]:
future_stock = FactInventory[
    FactInventory["LastRestocked"] > pd.Timestamp.today()
]

print(future_stock)

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [1002]:
negative_stock = FactInventory[
    FactInventory["StockAvailable"] < 0
]

print(negative_stock)

    InventoryID  ProductID  StoreID  StockAvailable  ReorderLevel  \
19           20         32       25             -34            82
20           21        812       28             -27            44
21           22        771       73             -40            80
22           23        545       56              -4           112
23           24        784       49             -10            21
24           25        858       46             -11           116
25           26        370       11             -20            47
26           27        863       36             -28            83
27           28        320        7             -48           100
28           29        368       76             -32           140
29           30         64       66             -34            65
30           31        880       39             -35           126
31           32        284       50             -30            45
32           33        817       40             -30            93
33           34        672       49              -6            51
34           35        224       43              -2            51
35           36        316       47             -23            43
36           37        858       10             -40            94
37           38        514       80             -38            39
38           39        657       28             -16           129
39           40        555       65             -36           137

   LastRestocked
19    2023-02-25
20    2025-07-17
21    2024-06-11
22    2023-06-14
23    2023-07-20
24    2024-11-20
25    2023-12-11
26    2024-02-11
27    2023-07-23
28    2024-02-27
29    2025-07-14
30    2025-05-07
31    2026-01-01
32    2025-03-06
33    2024-12-01
34    2025-03-28
35    2025-10-15
36    2025-08-09
37    2025-03-13
38    2024-08-26
39    2025-09-22

In [1004]:
negative_reorder = FactInventory[
    FactInventory["ReorderLevel"] <= 0
]

print(negative_reorder)

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [1006]:
median_date = FactInventory["LastRestocked"].median()

FactInventory.loc[
    FactInventory["LastRestocked"].isna(),
    "LastRestocked"
] = median_date

In [1008]:
median_date = FactInventory["LastRestocked"].median()

FactInventory.loc[
    FactInventory["LastRestocked"] > pd.Timestamp.today(),
    "LastRestocked"
] = median_date

In [1010]:
FactInventory.loc[
    FactInventory["StockAvailable"] < 0,
    "StockAvailable"
] = 0

In [1012]:
median_reorder = FactInventory.loc[
    FactInventory["ReorderLevel"] > 0,
    "ReorderLevel"
].median()

FactInventory.loc[
    FactInventory["ReorderLevel"] <= 0,
    "ReorderLevel"
] = median_reorder

In [1014]:
FactInventory[
    FactInventory["LastRestocked"].isna()
]

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [1016]:
FactInventory[
    FactInventory["StockAvailable"] < 0
]

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [1018]:
FactInventory[
    FactInventory["LastRestocked"] > pd.Timestamp.today()
]

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked]
Index: []

In [1020]:
inventory_check = FactInventory.merge(
    DimProduct_Enterprise[
        ["ProductID", "LaunchDate"]
    ],
    on="ProductID",
    how="left"
)

invalid_restock = inventory_check[
    inventory_check["LastRestocked"] <
    inventory_check["LaunchDate"]
]

print(invalid_restock)

       InventoryID  ProductID  StoreID  StockAvailable  ReorderLevel  \
1                2        803       59             453            70
4                5        279       26             583           114
5                6        429       56             236           129
16              17        429       27             115            81
26              27        863       36               0            83
...            ...        ...      ...             ...           ...
11982        11983        735       78              68            52
11987        11988        564       57             406            94
11988        11989         56       15             500            57
11992        11993        246       13             515            27
11994        11995        104       12             439           146

      LastRestocked LaunchDate
1        2024-03-29 2025-06-19
4        2023-03-23 2024-11-20
5        2024-07-28 2025-02-21
16       2023-06-02 2025-02-21
26       2024-02-11 2025-04-15
...             ...        ...
11982    2023-07-12 2024-08-09
11987    2024-03-22 2024-11-20
11988    2023-01-19 2025-04-08
11992    2023-04-14 2024-04-07
11994    2023-09-11 2023-11-21

[3149 rows x 7 columns]

In [1022]:
FactInventory = FactInventory.merge(
    DimProduct_Enterprise[
        ["ProductID", "LaunchDate"]
    ],
    on="ProductID",
    how="left"
)

FactInventory.loc[
    FactInventory["LastRestocked"] < FactInventory["LaunchDate"],
    "LastRestocked"
] = FactInventory.loc[
    FactInventory["LastRestocked"] < FactInventory["LaunchDate"],
    "LaunchDate"
]

FactInventory.drop(columns="LaunchDate", inplace=True)

In [1024]:
inventory_check = FactInventory.merge(
    DimProduct_Enterprise[
        ["ProductID", "LaunchDate"]
    ],
    on="ProductID",
    how="left"
)

invalid_restock = inventory_check[
    inventory_check["LastRestocked"] < inventory_check["LaunchDate"]
]

print(invalid_restock)

Empty DataFrame
Columns: [InventoryID, ProductID, StoreID, StockAvailable, ReorderLevel, LastRestocked, LaunchDate]
Index: []

In [127]:
FactInventory["LastRestocked"] = (
    FactInventory["LastRestocked"]
    .fillna(pd.Timestamp("1900-01-01"))
)

## Fact Shipments

In [1027]:
FactShipments["DispatchDate"] = pd.to_datetime(
    FactShipments["DispatchDate"],
    errors="coerce"
)

FactShipments["DeliveryDate"] = pd.to_datetime(
    FactShipments["DeliveryDate"],
    errors="coerce"
)

In [1029]:
invalid_order = FactShipments[
    ~FactShipments["OrderID"].isin(
        FactOrders["OrderID"]
    )
]

print(invalid_order)

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1031]:
missing_courier = FactShipments[
    FactShipments["Courier"].isna()
]

print(missing_courier)

    ShipmentID  OrderID Courier DispatchDate DeliveryDate DeliveryStatus
49          50       50     NaN   2024-05-24   2024-05-29      Delivered
50          51       51     NaN   2024-10-22   2024-10-28      Delivered
51          52       52     NaN   2023-10-14   2023-10-16      Delivered
52          53       53     NaN   2025-03-10   2025-03-17        Pending
53          54       54     NaN   2023-03-06   2023-03-12      Delivered
54          55       55     NaN   2025-08-10   2025-08-15      Delivered
55          56       56     NaN   2024-11-28   2024-12-05      Delivered
56          57       57     NaN   2025-09-22   2025-09-23      Delivered
57          58       58     NaN   2025-06-17   2025-06-20      Delivered
58          59       59     NaN   2026-04-26   2026-05-01      Delivered
59          60       60     NaN   2026-05-15   2026-05-20      Delivered
60          61       61     NaN   2025-11-18   2025-11-24      Delivered
61          62       62     NaN   2025-01-24   2025-01-29      Delivered
62          63       63     NaN   2026-11-09   2026-11-11      Delivered
63          64       64     NaN   2024-11-02   2024-11-07      Delivered
64          65       65     NaN   2024-06-23   2024-06-25      Delivered
65          66       66     NaN   2023-07-08   2023-07-12      Delivered
66          67       67     NaN   2026-10-22   2026-10-27      Delivered
67          68       68     NaN   2024-12-24   2024-12-26      Delivered
68          69       69     NaN   2024-12-18   2024-12-23      Delivered
69          70       70     NaN   2023-04-17   2023-04-20        Pending
70          71       71     NaN   2023-04-02   2023-04-07      Delivered
71          72       72     NaN   2024-09-19   2024-09-22      Delivered
72          73       73     NaN   2023-05-17   2023-05-20      Delivered
73          74       74     NaN   2026-06-23   2026-06-29      Delivered
74          75       75     NaN   2023-02-10   2023-02-16      Delivered
75          76       76     NaN   2025-07-11   2025-07-12      Delivered
76          77       77     NaN   2026-12-19   2026-12-22      Delivered
77          78       78     NaN   2026-02-08   2026-02-15      Delivered
78          79       79     NaN   2026-12-15   2026-12-18      Delivered
79          80       80     NaN   2024-10-27   2024-11-03      Delivered
80          81       81     NaN   2024-10-01   2024-10-02        Pending
81          82       82     NaN   2025-04-23   2025-04-25      Delivered
82          83       83     NaN   2026-05-22   2026-05-25      Delivered
83          84       84     NaN   2024-06-07   2024-06-10      Delivered
84          85       85     NaN   2023-04-02   2023-04-06      Delivered

In [1033]:
valid_couriers = [
    "BlueDart",
    "DTDC",
    "Delhivery",
    "Ecom Express",
    "XpressBees"
]

invalid_courier = FactShipments[
    ~FactShipments["Courier"].isin(valid_couriers)
]

print(invalid_courier)

    ShipmentID  OrderID Courier DispatchDate DeliveryDate DeliveryStatus
49          50       50     NaN   2024-05-24   2024-05-29      Delivered
50          51       51     NaN   2024-10-22   2024-10-28      Delivered
51          52       52     NaN   2023-10-14   2023-10-16      Delivered
52          53       53     NaN   2025-03-10   2025-03-17        Pending
53          54       54     NaN   2023-03-06   2023-03-12      Delivered
54          55       55     NaN   2025-08-10   2025-08-15      Delivered
55          56       56     NaN   2024-11-28   2024-12-05      Delivered
56          57       57     NaN   2025-09-22   2025-09-23      Delivered
57          58       58     NaN   2025-06-17   2025-06-20      Delivered
58          59       59     NaN   2026-04-26   2026-05-01      Delivered
59          60       60     NaN   2026-05-15   2026-05-20      Delivered
60          61       61     NaN   2025-11-18   2025-11-24      Delivered
61          62       62     NaN   2025-01-24   2025-01-29      Delivered
62          63       63     NaN   2026-11-09   2026-11-11      Delivered
63          64       64     NaN   2024-11-02   2024-11-07      Delivered
64          65       65     NaN   2024-06-23   2024-06-25      Delivered
65          66       66     NaN   2023-07-08   2023-07-12      Delivered
66          67       67     NaN   2026-10-22   2026-10-27      Delivered
67          68       68     NaN   2024-12-24   2024-12-26      Delivered
68          69       69     NaN   2024-12-18   2024-12-23      Delivered
69          70       70     NaN   2023-04-17   2023-04-20        Pending
70          71       71     NaN   2023-04-02   2023-04-07      Delivered
71          72       72     NaN   2024-09-19   2024-09-22      Delivered
72          73       73     NaN   2023-05-17   2023-05-20      Delivered
73          74       74     NaN   2026-06-23   2026-06-29      Delivered
74          75       75     NaN   2023-02-10   2023-02-16      Delivered
75          76       76     NaN   2025-07-11   2025-07-12      Delivered
76          77       77     NaN   2026-12-19   2026-12-22      Delivered
77          78       78     NaN   2026-02-08   2026-02-15      Delivered
78          79       79     NaN   2026-12-15   2026-12-18      Delivered
79          80       80     NaN   2024-10-27   2024-11-03      Delivered
80          81       81     NaN   2024-10-01   2024-10-02        Pending
81          82       82     NaN   2025-04-23   2025-04-25      Delivered
82          83       83     NaN   2026-05-22   2026-05-25      Delivered
83          84       84     NaN   2024-06-07   2024-06-10      Delivered
84          85       85     NaN   2023-04-02   2023-04-06      Delivered

In [1035]:
valid_status = [
    "Delivered",
    "Pending",
    "In Transit",
    "Returned"
]

invalid_status = FactShipments[
    ~FactShipments["DeliveryStatus"].isin(valid_status)
]

print(invalid_status)

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1037]:
future_dispatch = FactShipments[
    FactShipments["DispatchDate"] > pd.Timestamp.today()
]

print(future_dispatch)

       ShipmentID  OrderID     Courier DispatchDate DeliveryDate  \
16             17       17    BlueDart   2026-08-23   2026-08-25
19             20       20        DTDC   2026-09-11   2026-09-10
25             26       26  XpressBees   2026-08-06   2026-08-05
27             28       28  XpressBees   2026-09-03   2026-09-02
62             63       63         NaN   2026-11-09   2026-11-11
...           ...      ...         ...          ...          ...
24970       24971    24971  XpressBees   2026-11-03   2026-11-07
24975       24976    24976  XpressBees   2026-09-11   2026-09-16
24979       24980    24980   Delhivery   2026-10-24   2026-10-26
24981       24982    24982    BlueDart   2026-12-25   2026-12-28
24993       24994    24994        DTDC   2026-11-22   2026-11-29

      DeliveryStatus
16         Delivered
19        In Transit
25          Returned
27         Delivered
62         Delivered
...              ...
24970      Delivered
24975       Returned
24979      Delivered
24981      Delivered
24993      Delivered

[2877 rows x 6 columns]

In [1039]:
future_delivery = FactShipments[
    FactShipments["DeliveryDate"] > pd.Timestamp.today()
]

print(future_delivery)

       ShipmentID  OrderID     Courier DispatchDate DeliveryDate  \
16             17       17    BlueDart   2026-08-23   2026-08-25
19             20       20        DTDC   2026-09-11   2026-09-10
25             26       26  XpressBees   2026-08-06   2026-08-05
27             28       28  XpressBees   2026-09-03   2026-09-02
62             63       63         NaN   2026-11-09   2026-11-11
...           ...      ...         ...          ...          ...
24970       24971    24971  XpressBees   2026-11-03   2026-11-07
24975       24976    24976  XpressBees   2026-09-11   2026-09-16
24979       24980    24980   Delhivery   2026-10-24   2026-10-26
24981       24982    24982    BlueDart   2026-12-25   2026-12-28
24993       24994    24994        DTDC   2026-11-22   2026-11-29

      DeliveryStatus
16         Delivered
19        In Transit
25          Returned
27         Delivered
62         Delivered
...              ...
24970      Delivered
24975       Returned
24979      Delivered
24981      Delivered
24993      Delivered

[2936 rows x 6 columns]

In [1041]:
invalid_delivery = FactShipments[
    FactShipments["DeliveryDate"] <
    FactShipments["DispatchDate"]
]

print(invalid_delivery)

    ShipmentID  OrderID       Courier DispatchDate DeliveryDate DeliveryStatus
17          18       18     Delhivery   2026-03-13   2026-03-12      Delivered
18          19       19      BlueDart   2025-12-17   2025-12-16      Delivered
19          20       20          DTDC   2026-09-11   2026-09-10     In Transit
20          21       21     Delhivery   2025-11-09   2025-11-08      Delivered
21          22       22     Delhivery   2025-05-30   2025-05-29        Pending
22          23       23    XpressBees   2025-02-19   2025-02-18      Delivered
23          24       24          DTDC   2026-03-01   2026-02-28        Pending
24          25       25    XpressBees   2024-08-12   2024-08-11      Delivered
25          26       26    XpressBees   2026-08-06   2026-08-05       Returned
26          27       27  Ecom Express   2023-01-19   2023-01-18      Delivered
27          28       28    XpressBees   2026-09-03   2026-09-02      Delivered
28          29       29     Delhivery   2025-04-17   2025-04-16        Pending
29          30       30  Ecom Express   2023-04-09   2023-04-08     In Transit
30          31       31          DTDC   2025-06-03   2025-06-02        Pending
31          32       32    XpressBees   2023-01-10   2023-01-09      Delivered
32          33       33          DTDC   2024-07-27   2024-07-26      Delivered
33          34       34    XpressBees   2023-07-15   2023-07-14      Delivered
34          35       35      BlueDart   2024-04-24   2024-04-23      Delivered
35          36       36          DTDC   2023-10-25   2023-10-24      Delivered

In [1043]:
shipment_check = FactShipments.merge(
    FactOrders[
        ["OrderID", "OrderDateKey"]
    ],
    on="OrderID",
    how="left"
)

In [1045]:
shipment_check["OrderDate"] = pd.to_datetime(
    shipment_check["OrderDateKey"].astype(str),
    format="%Y%m%d",
    errors="coerce"
)

In [1047]:
invalid_dispatch = shipment_check[
    shipment_check["DispatchDate"] <
    shipment_check["OrderDate"]
]

print(invalid_dispatch)

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus, OrderDateKey, OrderDate]
Index: []

In [1049]:
text_columns = [
    "Courier",
    "DeliveryStatus"
]

for col in text_columns:
    FactShipments[col] = (
        FactShipments[col]
        .str.strip()
        .str.title()
    )

In [1051]:
mode_courier = FactShipments["Courier"].mode()[0]

FactShipments["Courier"] = (
    FactShipments["Courier"]
    .fillna(mode_courier)
)

In [1053]:
median_dispatch = FactShipments["DispatchDate"].median()

FactShipments.loc[
    FactShipments["DispatchDate"] > pd.Timestamp.today(),
    "DispatchDate"
] = median_dispatch

In [1055]:
median_delivery = FactShipments["DeliveryDate"].median()

FactShipments.loc[
    FactShipments["DeliveryDate"] > pd.Timestamp.today(),
    "DeliveryDate"
] = median_delivery

In [1057]:
FactShipments.loc[
    FactShipments["DeliveryDate"] <
    FactShipments["DispatchDate"],
    "DeliveryDate"
] = FactShipments.loc[
    FactShipments["DeliveryDate"] <
    FactShipments["DispatchDate"],
    "DispatchDate"
]

In [1059]:
mask = (
    shipment_check["DispatchDate"] <
    shipment_check["OrderDate"]
)

FactShipments.loc[
    mask,
    "DispatchDate"
] = shipment_check.loc[
    mask,
    "OrderDate"
].values

In [1061]:
shipment_status_check = FactShipments.merge(
    FactOrders[["OrderID", "OrderStatus"]],
    on="OrderID",
    how="left"
)

invalid_status_match = shipment_status_check[
    (shipment_status_check["OrderStatus"] == "Completed") &
    (shipment_status_check["DeliveryStatus"].isin(["Pending", "In Transit"]))
]

print(invalid_status_match)

       ShipmentID  OrderID       Courier DispatchDate DeliveryDate  \
2               3        3    Xpressbees   2025-12-24   2025-12-29
4               5        5     Delhivery   2024-08-07   2024-08-14
6               7        7      Bluedart   2024-10-14   2024-10-19
14             15       15      Bluedart   2025-01-09   2025-01-12
19             20       20          Dtdc   2024-12-29   2025-01-03
...           ...      ...           ...          ...          ...
24966       24967    24967  Ecom Express   2024-07-19   2024-07-24
24980       24981    24981  Ecom Express   2024-09-27   2024-09-30
24982       24983    24983    Xpressbees   2025-05-29   2025-05-30
24989       24990    24990    Xpressbees   2025-05-30   2025-06-05
24995       24996    24996          Dtdc   2023-01-17   2023-01-18

      DeliveryStatus OrderStatus
2         In Transit   Completed
4         In Transit   Completed
6         In Transit   Completed
14        In Transit   Completed
19        In Transit   Completed
...              ...         ...
24966        Pending   Completed
24980        Pending   Completed
24982        Pending   Completed
24989     In Transit   Completed
24995        Pending   Completed

[4043 rows x 7 columns]

In [1063]:
mode_courier = FactShipments["Courier"].mode()[0]

In [1065]:
FactShipments["Courier"] = (
    FactShipments["Courier"]
    .fillna(mode_courier)
)

In [1067]:
FactShipments[
    FactShipments["Courier"].isna()
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1069]:
FactShipments[
    FactShipments["DispatchDate"] >
    pd.Timestamp.today()
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1071]:
FactShipments[
    FactShipments["DeliveryDate"] >
    pd.Timestamp.today()
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1073]:
FactShipments[
    FactShipments["DeliveryDate"] <
    FactShipments["DispatchDate"]
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1075]:
shipment_status_check = FactShipments.merge(
    FactOrders[["OrderID","OrderStatus"]],
    on="OrderID",
    how="left"
)

mask = (
    shipment_status_check["OrderStatus"] == "Completed"
)

FactShipments.loc[
    mask,
    "DeliveryStatus"
] = "Delivered"

In [1077]:
shipment_status_check = FactShipments.merge(
    FactOrders[["OrderID","OrderStatus"]],
    on="OrderID",
    how="left"
)

invalid_status_match = shipment_status_check[
    (shipment_status_check["OrderStatus"]=="Completed") &
    (
        shipment_status_check["DeliveryStatus"]
        .isin(["Pending","In Transit"])
    )
]

print(invalid_status_match)

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus, OrderStatus]
Index: []

In [1079]:
FactShipments["Courier"].isna().sum()

0

In [1081]:
FactShipments[
    FactShipments["DispatchDate"] >
    pd.Timestamp.today()
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1083]:
FactShipments[
    FactShipments["DeliveryDate"] >
    pd.Timestamp.today()
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1085]:
FactShipments[
    FactShipments["DeliveryDate"] <
    FactShipments["DispatchDate"]
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus]
Index: []

In [1087]:
shipment_status_check = FactShipments.merge(
    FactOrders[["OrderID","OrderStatus"]],
    on="OrderID",
    how="left"
)

shipment_status_check[
    (shipment_status_check["OrderStatus"]=="Completed") &
    (shipment_status_check["DeliveryStatus"].isin(["Pending","In Transit"]))
]

Empty DataFrame
Columns: [ShipmentID, OrderID, Courier, DispatchDate, DeliveryDate, DeliveryStatus, OrderStatus]
Index: []

## FactMarketing

In [1090]:
invalid_promotion = FactMarketing[
    ~FactMarketing["PromotionID"].isin(
        DimPromotion["PromotionID"]
    )
]

print(invalid_promotion)

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions]
Index: []

In [1092]:
valid_channels = [
    "Google Ads",
    "Facebook",
    "Instagram",
    "YouTube",
    "Email",
    "SMS",
    "Affiliate"
]

invalid_channel = FactMarketing[
    ~FactMarketing["Channel"].isin(valid_channels)
]

print(invalid_channel)

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions]
Index: []

In [1094]:
FactMarketing["Channel"] = (
    FactMarketing["Channel"]
        .str.strip()
        .str.title()
)

In [1096]:
negative_cost = FactMarketing[
    FactMarketing["Cost"] < 0
]

print(negative_cost)

    CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
79          80           36  Google Ads  -52708.05       239222    9570
80          81           49  Google Ads  -74557.95       332332   16476
81          82           89    Facebook  -80512.66       260616   19773
82          83           23  Google Ads  -70418.07       126303   17758
83          84           60    Facebook  -64407.89       257056   20450
84          85          101  Google Ads  -74921.84       262103    7422
85          86          128   Instagram -167070.33        87606   22483
86          87           81   Affiliate -209896.19       395329   20645

    Conversions
79          572
80         4752
81         2466
82         1722
83         1265
84         2322
85         2428
86         3348

In [1098]:
negative_impressions = FactMarketing[
    FactMarketing["Impressions"] < 0
]

print(negative_impressions)

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions]
Index: []

In [1100]:
negative_clicks = FactMarketing[
    FactMarketing["Clicks"] < 0
]

print(negative_clicks)

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions]
Index: []

In [1102]:
negative_conversions = FactMarketing[
    FactMarketing["Conversions"] < 0
]

print(negative_conversions)

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions]
Index: []

In [1104]:
invalid_clicks = FactMarketing[
    FactMarketing["Clicks"] >
    FactMarketing["Impressions"]
]

print(invalid_clicks)

      CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
24            25           60     Youtube  161352.30        80930   82393
25            26           60   Instagram  179071.52        76267   79931
26            27           62   Affiliate   48759.04       366415  368915
27            28           75       Email   27330.49        78714   83126
28            29           80   Affiliate  233406.48       177618  182376
29            30           23   Instagram  155966.32        77801   82506
30            31           56    Facebook   46292.82       458303  462075
31            32           93         Sms   86961.55       272916  276317
32            33            1   Instagram   76304.69        30474   30712
33            34          106  Google Ads  134512.44       142388  144887
34            35           28         Sms  137532.18       499047  501153
35            36           80         Sms  173405.70       497416  498930
36            37          114  Google Ads   31196.49       437553  440653
37            38           24   Instagram   59553.68       198558  202639
38            39           87       Email  182233.49       323842  324294
39            40          104     Youtube   19772.81         7903   11412
40            41          144         Sms   35005.90       443186  446435
41            42           78   Affiliate  131558.77       191088  193990
42            43          118   Affiliate   48764.94       352818  354797
43            44           39   Affiliate  219904.86       264710  268713
44            45           75   Instagram  216058.62       195678  198413
45            46            8         Sms   77805.19       270900  275389
46            47          108  Google Ads  133453.93       383906  385942
47            48          101   Instagram  141042.20       390301  390713
48            49           12    Facebook  226370.49       227418  231359
60            61           39         Sms  233209.13         5248   21631
62            63           88   Affiliate  219461.68         7113   17439
69            70           61     Youtube   44263.95         5807   21168
129          130          131   Affiliate   35075.77        18754   21055
258          259           58       Email  104485.28         5048    5342
289          290            4     Youtube   38974.31        15599   19793
455          456           29   Instagram  134983.26        15823   19101
608          609           36   Affiliate   40166.61         7113   13528
643          644          109   Affiliate  222218.79         6353   12207
803          804           40       Email  234007.50         7418   18783
815          816           69   Instagram  184435.50        11019   18308
990          991            7         Sms  217564.21        13670   21423
1043        1044          105     Youtube  151361.02        11701   18333
1077        1078           44     Youtube  218395.70         9380   11053
1288        1289           93         Sms   50618.84        10151   15040
1321        1322          118    Facebook  152823.27        12921   21479
1426        1427           41    Facebook   55625.74        17215   23205
1460        1461          137   Affiliate   27975.06        10302   13919
1490        1491           67  Google Ads  140643.30         6373   15273
1585        1586          125    Facebook   29759.30        18547   24347
1672        1673          138   Instagram   99041.34        15227   18567
1731        1732           20   Instagram  227561.96        13058   20906
1767        1768           20  Google Ads   26320.42        20026   20889
1822        1823          114  Google Ads   18029.62        10610   11293
1858        1859           23       Email   71027.07        16220   16936
1889        1890           39     Youtube   24382.26         8714   23363

      Conversions
24            972
25           2193
26            854
27           1659
28           2028
29           4425
30           4003
31           3095
32            527
33           2545
34           3413
35           3881
36           2116
37            103
38            968
39           1021
40            938
41           2532
42           4494
43           1350
44           4090
45           4816
46             61
47            656
48           1744
60          21779
62          17722
69          21350
129          3826
258           592
289          3283
455          1591
608          3438
643          1574
803          1756
815           726
990          2666
1043         3755
1077          695
1288         3041
1321         3718
1426         4325
1460          227
1490         2981
1585         2265
1672         4539
1731         1111
1767          673
1822         2641
1858         3541
1889         3378

In [1106]:
invalid_conversions = FactMarketing[
    FactMarketing["Conversions"] >
    FactMarketing["Clicks"]
]

print(invalid_conversions)

    CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
59          60          126     Youtube  236625.82       178758   14726
60          61           39         Sms  233209.13         5248   21631
61          62          148  Google Ads   63926.95       273567    5850
62          63           88   Affiliate  219461.68         7113   17439
63          64           66   Instagram  163322.78       242273    1598
64          65            6         Sms  233087.47       287474   17940
65          66           86         Sms  213169.36        92407    6524
66          67           75         Sms  141823.05       222045   15192
67          68           87       Email  182671.50       165433   22009
68          69           45    Facebook  186855.39       242930   15737
69          70           61     Youtube   44263.95         5807   21168
70          71          125    Facebook  162702.48       450653   19311
71          72          143       Email  234624.68       249743    9037
72          73            1    Facebook  209747.41        44698    2824
73          74          150       Email   84801.95        46498   10263

    Conversions
59        14870
60        21779
61         5906
62        17722
63         1691
64        18023
65         6812
66        15344
67        22100
68        15885
69        21350
70        19536
71         9255
72         2878
73        10524

In [1108]:
invalid_cost = FactMarketing[
    FactMarketing["Cost"] <= 0
]

print(invalid_cost)

    CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
79          80           36  Google Ads  -52708.05       239222    9570
80          81           49  Google Ads  -74557.95       332332   16476
81          82           89    Facebook  -80512.66       260616   19773
82          83           23  Google Ads  -70418.07       126303   17758
83          84           60    Facebook  -64407.89       257056   20450
84          85          101  Google Ads  -74921.84       262103    7422
85          86          128   Instagram -167070.33        87606   22483
86          87           81   Affiliate -209896.19       395329   20645

    Conversions
79          572
80         4752
81         2466
82         1722
83         1265
84         2322
85         2428
86         3348

In [1110]:
FactMarketing["CTR"] = (
    FactMarketing["Clicks"] /
    FactMarketing["Impressions"]
)

invalid_ctr = FactMarketing[
    FactMarketing["CTR"] > 1
]

print(invalid_ctr)

      CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
24            25           60     Youtube  161352.30        80930   82393
25            26           60   Instagram  179071.52        76267   79931
26            27           62   Affiliate   48759.04       366415  368915
27            28           75       Email   27330.49        78714   83126
28            29           80   Affiliate  233406.48       177618  182376
29            30           23   Instagram  155966.32        77801   82506
30            31           56    Facebook   46292.82       458303  462075
31            32           93         Sms   86961.55       272916  276317
32            33            1   Instagram   76304.69        30474   30712
33            34          106  Google Ads  134512.44       142388  144887
34            35           28         Sms  137532.18       499047  501153
35            36           80         Sms  173405.70       497416  498930
36            37          114  Google Ads   31196.49       437553  440653
37            38           24   Instagram   59553.68       198558  202639
38            39           87       Email  182233.49       323842  324294
39            40          104     Youtube   19772.81         7903   11412
40            41          144         Sms   35005.90       443186  446435
41            42           78   Affiliate  131558.77       191088  193990
42            43          118   Affiliate   48764.94       352818  354797
43            44           39   Affiliate  219904.86       264710  268713
44            45           75   Instagram  216058.62       195678  198413
45            46            8         Sms   77805.19       270900  275389
46            47          108  Google Ads  133453.93       383906  385942
47            48          101   Instagram  141042.20       390301  390713
48            49           12    Facebook  226370.49       227418  231359
60            61           39         Sms  233209.13         5248   21631
62            63           88   Affiliate  219461.68         7113   17439
69            70           61     Youtube   44263.95         5807   21168
129          130          131   Affiliate   35075.77        18754   21055
258          259           58       Email  104485.28         5048    5342
289          290            4     Youtube   38974.31        15599   19793
455          456           29   Instagram  134983.26        15823   19101
608          609           36   Affiliate   40166.61         7113   13528
643          644          109   Affiliate  222218.79         6353   12207
803          804           40       Email  234007.50         7418   18783
815          816           69   Instagram  184435.50        11019   18308
990          991            7         Sms  217564.21        13670   21423
1043        1044          105     Youtube  151361.02        11701   18333
1077        1078           44     Youtube  218395.70         9380   11053
1288        1289           93         Sms   50618.84        10151   15040
1321        1322          118    Facebook  152823.27        12921   21479
1426        1427           41    Facebook   55625.74        17215   23205
1460        1461          137   Affiliate   27975.06        10302   13919
1490        1491           67  Google Ads  140643.30         6373   15273
1585        1586          125    Facebook   29759.30        18547   24347
1672        1673          138   Instagram   99041.34        15227   18567
1731        1732           20   Instagram  227561.96        13058   20906
1767        1768           20  Google Ads   26320.42        20026   20889
1822        1823          114  Google Ads   18029.62        10610   11293
1858        1859           23       Email   71027.07        16220   16936
1889        1890           39     Youtube   24382.26         8714   23363

      Conversions       CTR
24            972  1.018077
25           2193  1.048042
26            854  1.006823
27           1659  1.056051
28           2028  1.026788
29           4425  1.060475
30           4003  1.008230
31           3095  1.012462
32            527  1.007810
33           2545  1.017551
34           3413  1.004220
35           3881  1.003044
36           2116  1.007085
37            103  1.020553
38            968  1.001396
39           1021  1.444009
40            938  1.007331
41           2532  1.015187
42           4494  1.005609
43           1350  1.015122
44           4090  1.013977
45           4816  1.016571
46             61  1.005303
47            656  1.001056
48           1744  1.017329
60          21779  4.121761
62          17722  2.451708
69          21350  3.645256
129          3826  1.122694
258           592  1.058241
289          3283  1.268863
455          1591  1.207167
608          3438  1.901870
643          1574  1.921454
803          1756  2.532084
815           726  1.661494
990          2666  1.567154
1043         3755  1.566789
1077          695  1.178358
1288         3041  1.481627
1321         3718  1.662333
1426         4325  1.347952
1460          227  1.351097
1490         2981  2.396517
1585         2265  1.312719
1672         4539  1.219347
1731         1111  1.601011
1767          673  1.043094
1822         2641  1.064373
1858         3541  1.044143
1889         3378  2.681088

In [1112]:
FactMarketing["ConversionRate"] = (
    FactMarketing["Conversions"] /
    FactMarketing["Clicks"]
)

invalid_conversion_rate = FactMarketing[
    FactMarketing["ConversionRate"] > 1
]

print(invalid_conversion_rate)

    CampaignID  PromotionID     Channel       Cost  Impressions  Clicks  \
59          60          126     Youtube  236625.82       178758   14726
60          61           39         Sms  233209.13         5248   21631
61          62          148  Google Ads   63926.95       273567    5850
62          63           88   Affiliate  219461.68         7113   17439
63          64           66   Instagram  163322.78       242273    1598
64          65            6         Sms  233087.47       287474   17940
65          66           86         Sms  213169.36        92407    6524
66          67           75         Sms  141823.05       222045   15192
67          68           87       Email  182671.50       165433   22009
68          69           45    Facebook  186855.39       242930   15737
69          70           61     Youtube   44263.95         5807   21168
70          71          125    Facebook  162702.48       450653   19311
71          72          143       Email  234624.68       249743    9037
72          73            1    Facebook  209747.41        44698    2824
73          74          150       Email   84801.95        46498   10263

    Conversions       CTR  ConversionRate
59        14870  0.082380        1.009779
60        21779  4.121761        1.006842
61         5906  0.021384        1.009573
62        17722  2.451708        1.016228
63         1691  0.006596        1.058198
64        18023  0.062406        1.004627
65         6812  0.070601        1.044145
66        15344  0.068419        1.010005
67        22100  0.133039        1.004135
68        15885  0.064780        1.009405
69        21350  3.645256        1.008598
70        19536  0.042851        1.011651
71         9255  0.036185        1.024123
72         2878  0.063180        1.019122
73        10524  0.220719        1.025431

In [1114]:
FactMarketing.loc[
    FactMarketing["Cost"] < 0,
    "Cost"
] = (
    FactMarketing.loc[
        FactMarketing["Cost"] < 0,
        "Cost"
    ].abs()
)

In [1116]:
FactMarketing[
    FactMarketing["Cost"] < 0
]

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions, CTR, ConversionRate]
Index: []

In [1118]:
FactMarketing.loc[
    FactMarketing["Clicks"] >
    FactMarketing["Impressions"],
    "Clicks"
] = FactMarketing.loc[
    FactMarketing["Clicks"] >
    FactMarketing["Impressions"],
    "Impressions"
]

In [1120]:
FactMarketing[
    FactMarketing["Clicks"] >
    FactMarketing["Impressions"]
]

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions, CTR, ConversionRate]
Index: []

In [1122]:
FactMarketing.loc[
    FactMarketing["Conversions"] >
    FactMarketing["Clicks"],
    "Conversions"
] = FactMarketing.loc[
    FactMarketing["Conversions"] >
    FactMarketing["Clicks"],
    "Clicks"
]

In [1124]:
FactMarketing[
    FactMarketing["Conversions"] >
    FactMarketing["Clicks"]
]

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions, CTR, ConversionRate]
Index: []

In [1126]:
FactMarketing["CTR"] = (
    FactMarketing["Clicks"] /
    FactMarketing["Impressions"]
)

FactMarketing[
    FactMarketing["CTR"] > 1
]

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions, CTR, ConversionRate]
Index: []

In [1128]:
FactMarketing["ConversionRate"] = (
    FactMarketing["Conversions"] /
    FactMarketing["Clicks"]
)

FactMarketing[
    FactMarketing["ConversionRate"] > 1
]

Empty DataFrame
Columns: [CampaignID, PromotionID, Channel, Cost, Impressions, Clicks, Conversions, CTR, ConversionRate]
Index: []

In [1130]:
FactMarketing.drop(
    columns=[
        "CTR",
        "ConversionRate"
    ],
    inplace=True
)

## FactWebsiteTraffic

In [1133]:
FactWebsiteTraffic["VisitDate"] = pd.to_datetime(
    FactWebsiteTraffic["VisitDate"],
    errors="coerce"
)

In [1135]:
invalid_customer = FactWebsiteTraffic[
    ~FactWebsiteTraffic["CustomerID"].isin(
        DimCustomer_Enterprise["CustomerID"]
    )
]

print(invalid_customer)

     SessionID  CustomerID  VisitDate   Device TrafficSource  \
149        150         NaN 2026-02-21   Mobile        Direct
150        151         NaN 2025-04-26   Tablet       Organic
151        152         NaN 2026-03-09   Mobile       Organic
152        153         NaN 2025-07-07  Desktop     Instagram
153        154         NaN 2025-05-27  Desktop    Google Ads
154        155         NaN 2026-07-03   Tablet        Direct
155        156         NaN 2025-09-13   Tablet     Instagram
156        157         NaN 2024-04-02   Mobile      Referral
157        158         NaN 2023-12-21   Tablet    Google Ads
158        159         NaN 2023-11-25   Mobile    Google Ads
159        160         NaN 2025-08-02   Tablet     Instagram
160        161         NaN 2023-11-07  Desktop      Facebook
161        162         NaN 2024-01-19   Tablet      Referral

     SessionDuration_Min  PagesViewed Purchased
149                17.76           15       Yes
150                13.61            8       Yes
151                41.92           11       Yes
152                 9.30            9       Yes
153                26.73            9       Yes
154                41.92            6       Yes
155                41.79            6       Yes
156                43.09            8       Yes
157                 4.32           11       Yes
158                42.83           14       Yes
159                39.97            2       Yes
160                35.69            8       Yes
161                12.89            4       Yes

In [1137]:
missing_customer = FactWebsiteTraffic[
    FactWebsiteTraffic["CustomerID"].isna()
]

print(missing_customer)

     SessionID  CustomerID  VisitDate   Device TrafficSource  \
149        150         NaN 2026-02-21   Mobile        Direct
150        151         NaN 2025-04-26   Tablet       Organic
151        152         NaN 2026-03-09   Mobile       Organic
152        153         NaN 2025-07-07  Desktop     Instagram
153        154         NaN 2025-05-27  Desktop    Google Ads
154        155         NaN 2026-07-03   Tablet        Direct
155        156         NaN 2025-09-13   Tablet     Instagram
156        157         NaN 2024-04-02   Mobile      Referral
157        158         NaN 2023-12-21   Tablet    Google Ads
158        159         NaN 2023-11-25   Mobile    Google Ads
159        160         NaN 2025-08-02   Tablet     Instagram
160        161         NaN 2023-11-07  Desktop      Facebook
161        162         NaN 2024-01-19   Tablet      Referral

     SessionDuration_Min  PagesViewed Purchased
149                17.76           15       Yes
150                13.61            8       Yes
151                41.92           11       Yes
152                 9.30            9       Yes
153                26.73            9       Yes
154                41.92            6       Yes
155                41.79            6       Yes
156                43.09            8       Yes
157                 4.32           11       Yes
158                42.83           14       Yes
159                39.97            2       Yes
160                35.69            8       Yes
161                12.89            4       Yes

In [1139]:
duplicate_session = FactWebsiteTraffic[
    FactWebsiteTraffic["SessionID"].duplicated(
        keep=False
    )
]

print(duplicate_session)

      SessionID  CustomerID  VisitDate  Device TrafficSource  \
4998       4999      2016.0 2025-01-02  Mobile       Organic
4999       4999      3404.0 2023-01-08  Tablet      Referral
5000       4999      2595.0 2024-11-21  Mobile      Facebook

      SessionDuration_Min  PagesViewed Purchased
4998                18.44            8        No
4999                44.11           10        No
5000                25.96            4        No

In [1141]:
future_visit = FactWebsiteTraffic[
    FactWebsiteTraffic["VisitDate"] >
    pd.Timestamp.today()
]

print(future_visit)

      SessionID  CustomerID  VisitDate   Device TrafficSource  \
3             4      1058.0 2026-10-28   Mobile      Referral
17           18      4994.0 2026-09-24   Mobile       Organic
36           37      3260.0 2026-10-24  Desktop      Facebook
49           50       594.0 2026-08-03  Desktop      Facebook
65           66      1660.0 2026-08-23   Tablet      Facebook
...         ...         ...        ...      ...           ...
9963       9964      1371.0 2026-12-04   Mobile        Direct
9978       9979      4199.0 2026-11-09   Mobile      Facebook
9985       9986       934.0 2026-07-28  Desktop      Referral
9986       9987      4171.0 2026-11-20   Mobile      Referral
9991       9992      4951.0 2026-11-08  Desktop        Direct

      SessionDuration_Min  PagesViewed Purchased
3                   20.14            9        No
17                  21.09            9       Yes
36                  -1.49           14        No
49                  21.25           12       Yes
65                  28.38            0        No
...                   ...          ...       ...
9963                10.70           10        No
9978                25.66            8        No
9985                40.93            8        No
9986                36.32            9        No
9991                19.14            5        No

[1093 rows x 8 columns]

In [1143]:
negative_duration = FactWebsiteTraffic[
    FactWebsiteTraffic["SessionDuration_Min"] < 0
]

print(negative_duration)

    SessionID  CustomerID  VisitDate   Device TrafficSource  \
19         20      4291.0 2026-05-22   Tablet    Google Ads
20         21      4644.0 2023-11-21   Tablet     Instagram
21         22      2716.0 2025-03-28   Mobile    Google Ads
22         23      4764.0 2026-05-16   Tablet       Organic
23         24      1985.0 2023-10-29  Desktop    Google Ads
24         25      4904.0 2023-03-17  Desktop        Direct
25         26      2665.0 2024-02-18   Tablet        Direct
26         27      1950.0 2023-07-18  Desktop         Email
27         28      4665.0 2023-12-15   Mobile         Email
28         29      4820.0 2025-05-24   Mobile        Direct
29         30      3057.0 2024-12-27  Desktop     Instagram
30         31       344.0 2024-02-29   Mobile      Facebook
31         32      2227.0 2026-05-21  Desktop        Direct
32         33       960.0 2024-07-07   Tablet         Email
33         34      1108.0 2024-03-25   Tablet       Organic
34         35       296.0 2025-04-25   Mobile      Referral
35         36      2913.0 2024-08-02  Desktop         Email
36         37      3260.0 2026-10-24  Desktop      Facebook
37         38       545.0 2026-04-16   Tablet     Instagram
38         39      4393.0 2024-03-17  Desktop        Direct

    SessionDuration_Min  PagesViewed Purchased
19                -9.02           10       Yes
20                -8.38           11        No
21                -3.93            6        No
22                -5.61            6        No
23                -9.83            7        No
24                -7.84            6        No
25                -6.73            7       Yes
26                -2.86           10        No
27                -9.13            4        No
28                -4.99           10        No
29                -9.12           13       Yes
30                -8.66            6        No
31                -8.95           10        No
32                -4.06           13        No
33                -9.24            3        No
34                -8.69            5        No
35                -5.07           10        No
36                -1.49           14        No
37                -3.38           15       Yes
38                -9.35           14        No

In [1145]:
negative_pages = FactWebsiteTraffic[
    FactWebsiteTraffic["PagesViewed"] < 0
]

print(negative_pages)

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1147]:
valid_devices = [
    "Desktop",
    "Mobile",
    "Tablet"
]

invalid_device = FactWebsiteTraffic[
    ~FactWebsiteTraffic["Device"].isin(valid_devices)
]

print(invalid_device)

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1149]:
valid_sources = [
    "Google Ads",
    "Facebook",
    "Instagram",
    "Organic",
    "Referral",
    "Email",
    "Direct"
]

invalid_source = FactWebsiteTraffic[
    ~FactWebsiteTraffic["TrafficSource"].isin(valid_sources)
]

print(invalid_source)

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1151]:
valid_purchase = [
    "Yes",
    "No"
]

invalid_purchase = FactWebsiteTraffic[
    ~FactWebsiteTraffic["Purchased"].isin(valid_purchase)
]

print(invalid_purchase)

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1153]:
text_columns = [
    "Device",
    "TrafficSource",
    "Purchased"
]

for col in text_columns:
    FactWebsiteTraffic[col] = (
        FactWebsiteTraffic[col]
        .str.strip()
        .str.title()
    )

In [1155]:
invalid_purchase_pages = FactWebsiteTraffic[
    (FactWebsiteTraffic["Purchased"] == "Yes") &
    (FactWebsiteTraffic["PagesViewed"] == 0)
]

print(invalid_purchase_pages)

     SessionID  CustomerID  VisitDate   Device TrafficSource  \
60          61       631.0 2025-06-13  Desktop       Organic
63          64      4886.0 2025-12-10  Desktop      Facebook
69          70      4588.0 2025-09-13  Desktop       Organic
70          71      1099.0 2026-01-14   Tablet      Referral
75          76      2345.0 2024-07-22   Tablet         Email
77          78      4801.0 2023-02-27   Tablet    Google Ads
78          79       790.0 2026-06-17  Desktop    Google Ads
79          80       381.0 2024-05-25   Mobile    Google Ads
87          88      4044.0 2024-02-23  Desktop      Referral
93          94      4503.0 2023-03-21   Mobile       Organic
106        107       853.0 2026-08-30   Mobile     Instagram

     SessionDuration_Min  PagesViewed Purchased
60                 32.29            0       Yes
63                 42.62            0       Yes
69                 21.18            0       Yes
70                 10.98            0       Yes
75                 32.27            0       Yes
77                 23.22            0       Yes
78                 13.56            0       Yes
79                  4.01            0       Yes
87                 13.26            0       Yes
93                 40.50            0       Yes
106                22.02            0       Yes

In [1157]:
invalid_duration = FactWebsiteTraffic[
    FactWebsiteTraffic["SessionDuration_Min"] <= 0
]

print(invalid_duration)

    SessionID  CustomerID  VisitDate   Device TrafficSource  \
19         20      4291.0 2026-05-22   Tablet    Google Ads
20         21      4644.0 2023-11-21   Tablet     Instagram
21         22      2716.0 2025-03-28   Mobile    Google Ads
22         23      4764.0 2026-05-16   Tablet       Organic
23         24      1985.0 2023-10-29  Desktop    Google Ads
24         25      4904.0 2023-03-17  Desktop        Direct
25         26      2665.0 2024-02-18   Tablet        Direct
26         27      1950.0 2023-07-18  Desktop         Email
27         28      4665.0 2023-12-15   Mobile         Email
28         29      4820.0 2025-05-24   Mobile        Direct
29         30      3057.0 2024-12-27  Desktop     Instagram
30         31       344.0 2024-02-29   Mobile      Facebook
31         32      2227.0 2026-05-21  Desktop        Direct
32         33       960.0 2024-07-07   Tablet         Email
33         34      1108.0 2024-03-25   Tablet       Organic
34         35       296.0 2025-04-25   Mobile      Referral
35         36      2913.0 2024-08-02  Desktop         Email
36         37      3260.0 2026-10-24  Desktop      Facebook
37         38       545.0 2026-04-16   Tablet     Instagram
38         39      4393.0 2024-03-17  Desktop        Direct

    SessionDuration_Min  PagesViewed Purchased
19                -9.02           10       Yes
20                -8.38           11        No
21                -3.93            6        No
22                -5.61            6        No
23                -9.83            7        No
24                -7.84            6        No
25                -6.73            7       Yes
26                -2.86           10        No
27                -9.13            4        No
28                -4.99           10        No
29                -9.12           13       Yes
30                -8.66            6        No
31                -8.95           10        No
32                -4.06           13        No
33                -9.24            3        No
34                -8.69            5        No
35                -5.07           10        No
36                -1.49           14        No
37                -3.38           15       Yes
38                -9.35           14        No

In [1159]:
invalid_purchase_duration = FactWebsiteTraffic[
    (FactWebsiteTraffic["Purchased"] == "Yes") &
    (FactWebsiteTraffic["SessionDuration_Min"] <= 0)
]

print(invalid_purchase_duration)

    SessionID  CustomerID  VisitDate   Device TrafficSource  \
19         20      4291.0 2026-05-22   Tablet    Google Ads
25         26      2665.0 2024-02-18   Tablet        Direct
29         30      3057.0 2024-12-27  Desktop     Instagram
37         38       545.0 2026-04-16   Tablet     Instagram

    SessionDuration_Min  PagesViewed Purchased
19                -9.02           10       Yes
25                -6.73            7       Yes
29                -9.12           13       Yes
37                -3.38           15       Yes

In [1161]:
missing_customer_purchase = FactWebsiteTraffic[
    (FactWebsiteTraffic["Purchased"] == "Yes") &
    (FactWebsiteTraffic["CustomerID"].isna())
]

print(missing_customer_purchase)

     SessionID  CustomerID  VisitDate   Device TrafficSource  \
149        150         NaN 2026-02-21   Mobile        Direct
150        151         NaN 2025-04-26   Tablet       Organic
151        152         NaN 2026-03-09   Mobile       Organic
152        153         NaN 2025-07-07  Desktop     Instagram
153        154         NaN 2025-05-27  Desktop    Google Ads
154        155         NaN 2026-07-03   Tablet        Direct
155        156         NaN 2025-09-13   Tablet     Instagram
156        157         NaN 2024-04-02   Mobile      Referral
157        158         NaN 2023-12-21   Tablet    Google Ads
158        159         NaN 2023-11-25   Mobile    Google Ads
159        160         NaN 2025-08-02   Tablet     Instagram
160        161         NaN 2023-11-07  Desktop      Facebook
161        162         NaN 2024-01-19   Tablet      Referral

     SessionDuration_Min  PagesViewed Purchased
149                17.76           15       Yes
150                13.61            8       Yes
151                41.92           11       Yes
152                 9.30            9       Yes
153                26.73            9       Yes
154                41.92            6       Yes
155                41.79            6       Yes
156                43.09            8       Yes
157                 4.32           11       Yes
158                42.83           14       Yes
159                39.97            2       Yes
160                35.69            8       Yes
161                12.89            4       Yes

In [1163]:
FactWebsiteTraffic["CustomerID"] = (
    FactWebsiteTraffic["CustomerID"]
    .fillna(-1)
)

In [1165]:
duplicates = FactWebsiteTraffic[
    FactWebsiteTraffic["SessionID"].duplicated()
].index

next_id = FactWebsiteTraffic["SessionID"].max() + 1

FactWebsiteTraffic.loc[
    duplicates,
    "SessionID"
] = range(
    next_id,
    next_id + len(duplicates)
)

In [1167]:
median_date = FactWebsiteTraffic["VisitDate"].median()

FactWebsiteTraffic.loc[
    FactWebsiteTraffic["VisitDate"] > pd.Timestamp.today(),
    "VisitDate"
] = median_date

In [1169]:
median_duration = FactWebsiteTraffic.loc[
    FactWebsiteTraffic["SessionDuration_Min"] > 0,
    "SessionDuration_Min"
].median()

FactWebsiteTraffic.loc[
    FactWebsiteTraffic["SessionDuration_Min"] <= 0,
    "SessionDuration_Min"
] = median_duration

In [1171]:
FactWebsiteTraffic.loc[
    (FactWebsiteTraffic["Purchased"] == "Yes") &
    (FactWebsiteTraffic["PagesViewed"] == 0),
    "PagesViewed"
] = 1

In [1173]:
FactWebsiteTraffic[
    FactWebsiteTraffic["CustomerID"] == -1
]

,SessionID,CustomerID,VisitDate,Device,TrafficSource,SessionDuration_Min,PagesViewed,Purchased
149,150,-1.0,2026-02-21,Mobile,Direct,17.76,15,Yes
150,151,-1.0,2025-04-26,Tablet,Organic,13.61,8,Yes
151,152,-1.0,2026-03-09,Mobile,Organic,41.92,11,Yes
152,153,-1.0,2025-07-07,Desktop,Instagram,9.30,9,Yes
153,154,-1.0,2025-05-27,Desktop,Google Ads,26.73,9,Yes
154,155,-1.0,2026-07-03,Tablet,Direct,41.92,6,Yes
155,156,-1.0,2025-09-13,Tablet,Instagram,41.79,6,Yes
156,157,-1.0,2024-04-02,Mobile,Referral,43.09,8,Yes
157,158,-1.0,2023-12-21,Tablet,Google Ads,4.32,11,Yes
158,159,-1.0,2023-11-25,Mobile,Google Ads,42.83,14,Yes
159,160,-1.0,2025-08-02,Tablet,Instagram,39.97,2,Yes
160,161,-1.0,2023-11-07,Desktop,Facebook,35.69,8,Yes
161,162,-1.0,2024-01-19,Tablet,Referral,12.89,4,Yes

In [1175]:
FactWebsiteTraffic[
    FactWebsiteTraffic["SessionID"].duplicated()
]

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1177]:
FactWebsiteTraffic[
    FactWebsiteTraffic["VisitDate"] > pd.Timestamp.today()
]

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1179]:
FactWebsiteTraffic[
    FactWebsiteTraffic["SessionDuration_Min"] <= 0
]

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1181]:
FactWebsiteTraffic[
    (FactWebsiteTraffic["Purchased"] == "Yes") &
    (FactWebsiteTraffic["PagesViewed"] == 0)
]

Empty DataFrame
Columns: [SessionID, CustomerID, VisitDate, Device, TrafficSource, SessionDuration_Min, PagesViewed, Purchased]
Index: []

In [1183]:
FactWebsiteTraffic[
    FactWebsiteTraffic["CustomerID"] == -1
]

,SessionID,CustomerID,VisitDate,Device,TrafficSource,SessionDuration_Min,PagesViewed,Purchased
149,150,-1.0,2026-02-21,Mobile,Direct,17.76,15,Yes
150,151,-1.0,2025-04-26,Tablet,Organic,13.61,8,Yes
151,152,-1.0,2026-03-09,Mobile,Organic,41.92,11,Yes
152,153,-1.0,2025-07-07,Desktop,Instagram,9.30,9,Yes
153,154,-1.0,2025-05-27,Desktop,Google Ads,26.73,9,Yes
154,155,-1.0,2026-07-03,Tablet,Direct,41.92,6,Yes
155,156,-1.0,2025-09-13,Tablet,Instagram,41.79,6,Yes
156,157,-1.0,2024-04-02,Mobile,Referral,43.09,8,Yes
157,158,-1.0,2023-12-21,Tablet,Google Ads,4.32,11,Yes
158,159,-1.0,2023-11-25,Mobile,Google Ads,42.83,14,Yes
159,160,-1.0,2025-08-02,Tablet,Instagram,39.97,2,Yes
160,161,-1.0,2023-11-07,Desktop,Facebook,35.69,8,Yes
161,162,-1.0,2024-01-19,Tablet,Referral,12.89,4,Yes

In [117]:
FactWebsiteTraffic = FactWebsiteTraffic.drop_duplicates(
    subset="SessionID",
    keep="first"
)

In [119]:
FactWebsiteTraffic = FactWebsiteTraffic.drop_duplicates()

In [121]:
FactWebsiteTraffic["CustomerID"] = FactWebsiteTraffic["CustomerID"].fillna(0).astype(int)

In [123]:
print(FactWebsiteTraffic["CustomerID"].isnull().sum())
print((FactWebsiteTraffic["CustomerID"] == 0).sum())

0
13

## Importing the Cleaned Data

In [135]:
DimCategory.to_csv("DimCategory.csv", index=False)
DimRegion.to_csv("DimRegion.csv", index=False)
DimPromotion.to_csv("DimPromotion.csv", index=False)
DimSupplier_Enterprise.to_csv("DimSupplier_Enterprise.csv", index=False)
DimStore_Enterprise.to_csv("DimStore_Enterprise.csv", index=False)
DimEmployee_Enterprise.to_csv("DimEmployee_Enterprise.csv", index=False)
DimDate.to_csv("DimDate.csv", index=False)
DimCustomer_Enterprise.to_csv("DimCustomer_Enterprise.csv", index=False)
DimProduct_Enterprise.to_csv("DimProduct_Enterprise.csv", index=False)

FactOrders.to_csv("FactOrders.csv", index=False)
FactOrderDetails.to_csv("FactOrderDetails.csv", index=False)
FactPayments.to_csv("FactPayments.csv", index=False)
FactReturns.to_csv("FactReturns.csv", index=False)
FactInventory.to_csv("FactInventory.csv", index=False)
FactShipments.to_csv("FactShipments.csv", index=False)
FactMarketing.to_csv("FactMarketing.csv", index=False)
FactWebsiteTraffic.to_csv("FactWebsiteTraffic.csv", index=False)

In [18]:
import os

print(os.getcwd())

C:\Users\saisr

In [20]:
import os

files = os.listdir()

for file in files:
    if file.endswith(".csv"):
        print(file)

annual survey.csv
cars.csv
cars.csv.csv
customers_clean.csv
DimCategory.csv
DimCustomer_Enterprise.csv
DimDate.csv
DimEmployee_Enterprise.csv
DimProduct_Enterprise.csv
DimPromotion.csv
DimRegion.csv
DimStore_Enterprise.csv
DimSupplier_Enterprise.csv
FactInventory.csv
FactMarketing.csv
FactOrderDetails.csv
FactOrders.csv
FactPayments.csv
FactReturns.csv
FactShipments.csv
FactWebsiteTraffic.csv
netflix_titles.csv
sample_data.csv

In [54]:
FactWebsiteTraffic.columns

Index(['SessionID', 'CustomerID', 'VisitDate', 'Device', 'TrafficSource',
       'SessionDuration_Min', 'PagesViewed', 'Purchased'],
      dtype='object')

In [56]:
import pandas as pd

df = pd.read_csv("FactWebsiteTraffic.csv")

print("Total Rows:", len(df))

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate SessionID:", df["SessionID"].duplicated().sum())

print("\nInvalid VisitDate:")
df["VisitDate"] = pd.to_datetime(df["VisitDate"], errors="coerce")
print(df["VisitDate"].isnull().sum())

print("\nPurchased Values:")
print(df["Purchased"].value_counts(dropna=False))

Total Rows: 10000

Missing Values:
SessionID               0
CustomerID             13
VisitDate               0
Device                  0
TrafficSource           0
SessionDuration_Min     0
PagesViewed             0
Purchased               0
dtype: int64

Duplicate SessionID: 2

Invalid VisitDate:
0

Purchased Values:
Purchased
No     8171
Yes    1829
Name: count, dtype: int64

In [58]:
problem_rows = df[
    df.isnull().any(axis=1)
]

problem_rows

,SessionID,CustomerID,VisitDate,Device,TrafficSource,SessionDuration_Min,PagesViewed,Purchased
149,150,NaN,2026-02-21,Mobile,Direct,17.76,15,Yes
150,151,NaN,2025-04-26,Tablet,Organic,13.61,8,Yes
151,152,NaN,2026-03-09,Mobile,Organic,41.92,11,Yes
152,153,NaN,2025-07-07,Desktop,Instagram,9.30,9,Yes
153,154,NaN,2025-05-27,Desktop,Google Ads,26.73,9,Yes
154,155,NaN,2026-07-03,Tablet,Direct,41.92,6,Yes
155,156,NaN,2025-09-13,Tablet,Instagram,41.79,6,Yes
156,157,NaN,2024-04-02,Mobile,Referral,43.09,8,Yes
157,158,NaN,2023-12-21,Tablet,Google Ads,4.32,11,Yes
158,159,NaN,2023-11-25,Mobile,Google Ads,42.83,14,Yes
159,160,NaN,2025-08-02,Tablet,Instagram,39.97,2,Yes
160,161,NaN,2023-11-07,Desktop,Facebook,35.69,8,Yes
161,162,NaN,2024-01-19,Tablet,Referral,12.89,4,Yes

In [60]:
df[df.duplicated(subset="SessionID", keep=False)].sort_values("SessionID")

,SessionID,CustomerID,VisitDate,Device,TrafficSource,SessionDuration_Min,PagesViewed,Purchased
4998,4999,2016.0,2025-01-02,Mobile,Organic,18.44,8,No
4999,4999,3404.0,2023-01-08,Tablet,Referral,44.11,10,No
5000,4999,2595.0,2024-11-21,Mobile,Facebook,25.96,4,No

In [62]:
df = df.drop_duplicates(subset="SessionID", keep="first")

In [64]:
import pandas as pd

traffic = pd.read_csv("FactWebsiteTraffic.csv")

print("Original Shape :", traffic.shape)
traffic.head()

Original Shape : (10000, 8)

,SessionID,CustomerID,VisitDate,Device,TrafficSource,SessionDuration_Min,PagesViewed,Purchased
0,1,3001.0,2026-03-20,Mobile,Direct,8.92,8,Yes
1,2,4456.0,2025-04-08,Mobile,Organic,32.35,2,Yes
2,3,2425.0,2024-06-11,Mobile,Organic,18.57,3,Yes
3,4,1058.0,2026-10-28,Mobile,Referral,20.14,9,No
4,5,3512.0,2025-07-08,Desktop,Referral,10.88,12,Yes

In [66]:
print("="*60)
print("DATA QUALITY REPORT")
print("="*60)

print("\nDuplicate SessionID :", traffic["SessionID"].duplicated().sum())

print("\nMissing Values")
print(traffic.isnull().sum())

print("\nPurchased Values")
print(traffic["Purchased"].value_counts(dropna=False))

print("\nInvalid VisitDate")

traffic["VisitDate"] = pd.to_datetime(
    traffic["VisitDate"],
    errors="coerce"
)

print(traffic["VisitDate"].isnull().sum())

============================================================
DATA QUALITY REPORT
============================================================

Duplicate SessionID : 2

Missing Values
SessionID               0
CustomerID             13
VisitDate               0
Device                  0
TrafficSource           0
SessionDuration_Min     0
PagesViewed             0
Purchased               0
dtype: int64

Purchased Values
Purchased
No     8171
Yes    1829
Name: count, dtype: int64

Invalid VisitDate
0

In [68]:
traffic = traffic.drop_duplicates(
    subset="SessionID",
    keep="first"
)

In [70]:
traffic["Purchased"] = (
    traffic["Purchased"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [72]:
traffic = traffic[
    traffic["Purchased"].isin(["Yes","No"])
]

In [74]:
traffic = traffic.drop_duplicates()

In [76]:
print("="*60)
print("AFTER CLEANING")
print("="*60)

print("Rows :", len(traffic))

print("Duplicate SessionID :",
      traffic["SessionID"].duplicated().sum())

print("Missing Values")

print(traffic.isnull().sum())

============================================================
AFTER CLEANING
============================================================
Rows : 9998
Duplicate SessionID : 0
Missing Values
SessionID               0
CustomerID             13
VisitDate               0
Device                  0
TrafficSource           0
SessionDuration_Min     0
PagesViewed             0
Purchased               0
dtype: int64

In [78]:
traffic.to_csv(
    "FactWebsiteTraffic_Clean.csv",
    index=False
)

In [80]:
clean_df = pd.read_csv("FactWebsiteTraffic_Clean.csv")

print("Rows:", len(clean_df))
print("Duplicate SessionID:", clean_df["SessionID"].duplicated().sum())
print(clean_df.isnull().sum())

Rows: 9998
Duplicate SessionID: 0
SessionID               0
CustomerID             13
VisitDate               0
Device                  0
TrafficSource           0
SessionDuration_Min     0
PagesViewed             0
Purchased               0
dtype: int64

In [82]:
traffic["CustomerID"] = traffic["CustomerID"].fillna(0).astype(int)

In [84]:
print(traffic["CustomerID"].isnull().sum())
print((traffic["CustomerID"] == 0).sum())

0
13

In [2]:
traffic.to_csv("FactWebsiteTraffic_Clean.csv", index=False)

NameError: name 'traffic' is not defined